'use client';
import {useState} from 'react';
type Account={id:string;name:string;email:string;state:string;trialEndsAt:string;teamMember:boolean;protected:boolean};
export default function AccountAccessPanel(){
 const [email,setEmail]=useState(''),[industry,setIndustry]=useState('legal'),[accounts,setAccounts]=useState<Account[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function lookup(){const response=await fetch(`/api/admin/accounts?email=${encodeURIComponent(email.trim())}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setAccounts(data.accounts);return data.accounts as Account[]}
 async function search(){setBusy(true);setMessage('');try{const found=await lookup();if(!found.length)setMessage('No account found. Ask this person to create their sign-in at /login, then search the same email here.')}catch(e){setMessage(e instanceof Error?e.message:'Lookup failed')}finally{setBusy(false)}}
 async function change(id:string,action:string){setBusy(true);setMessage('');try{const response=await fetch('/api/admin/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,industry})});const data=await response.json();if(!response.ok)throw Error(data.error);await lookup();setMessage(action==='resume'?'Access unlocked. An active trial or subscription is still required.':'Account updated. No charge or email was sent.')}catch(e){setMessage(e instanceof Error?e.message:'Update failed')}finally{setBusy(false)}}
 return <section className="account-access-panel"><header><span className="eyebrow">PLATFORM OWNER</span><h2>Accounts & free trials</h2><p>Give an existing sign-in its own workspace and 30 free days. You can extend a trial, lock access, or unlock it here.</p></header><p>The person creates their own sign-in at <a href="/login" target="_blank" rel="noreferrer">pacificacrm.com/login</a>. Their contacts and office calendar stay separate from yours. Trial expiry blocks CRM access; it never creates a charge.</p><form onSubmit={e=>{e.preventDefault();void search()}} className="office-form"><label>Sign-in email<input type="email" required value={email} onChange={e=>{setEmail(e.target.value);setAccounts([])}}/></label><button disabled={busy}>Find account</button></form><label>New workspace type<select value={industry} onChange={e=>setIndustry(e.target.value)}><option value="legal">Legal / immigration office</option><option value="insurance">Insurance agency</option><option value="general">General business</option></select></label>{accounts.map(account=><article className="office-item" key={account.id}><div><b>{account.name||account.email}</b><p>{account.email} · {account.state}</p>{account.trialEndsAt&&<p>Trial ends {new Date(account.trialEndsAt).toLocaleString()}</p>}</div>{account.protected?<span>Protected owner</span>:account.teamMember?<span>Manage through their workspace owner</span>:<div><button disabled={busy} onClick={()=>void change(account.id,account.state==='unmanaged'?'grant-trial':'extend-trial')}>{account.state==='unmanaged'?'Start 30 free days':'Extend 30 days'}</button><button disabled={busy} onClick={()=>void change(account.id,account.state==='paused'?'resume':'pause')}>{account.state==='paused'?'Unlock access':'Lock access'}</button></div>}</article>)}<p role="status">{message}</p></section>
}
