'use client';
import {useState} from 'react';
type Account={id:string;name:string;email:string;state:string;scope:string;permanent:boolean;trialEndsAt:string;teamMember:boolean;protected:boolean};
export default function AccountAccessPanel(){
 const [email,setEmail]=useState(''),[industry,setIndustry]=useState('insurance'),[accounts,setAccounts]=useState<Account[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [duration,setDuration]=useState('30'),[days,setDays]=useState(30),[expires,setExpires]=useState(''),[scope,setScope]=useState('full');
 async function lookup(){const response=await fetch(`/api/admin/accounts?email=${encodeURIComponent(email.trim())}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);setAccounts(data.accounts);return data.accounts as Account[]}
 async function search(){setBusy(true);setMessage('');try{const found=await lookup();if(!found.length)setMessage('Ask this person to create their sign-in at /login, then search the same email.')}catch(e){setMessage(e instanceof Error?e.message:'Lookup failed')}finally{setBusy(false)}}
 async function change(id:string,action:string){setBusy(true);setMessage('');try{
  const expiresAt=duration==='date'&&expires?new Date(expires).toISOString():undefined;
  if(action==='set-access'&&duration==='date'&&!expiresAt)throw Error('Choose an expiry date.');
  const response=await fetch('/api/admin/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:action==='set-access'&&duration==='permanent'?'grant-permanent':action,industry,scope,days:duration==='custom'?days:/^\d+$/.test(duration)?Number(duration):30,expiresAt})});const data=await response.json();if(!response.ok)throw Error(data.error);await lookup();setMessage('Access updated. No charge or email was sent.');
 }catch(e){setMessage(e instanceof Error?e.message:'Update failed')}finally{setBusy(false)}}
 return <section className="account-access-panel"><header><span className="eyebrow">PLATFORM OWNER</span><h2>Accounts & trials</h2><p>Set permanent access, a trial or a custom expiry. Each account gets its own workspace.</p></header><form onSubmit={e=>{e.preventDefault();void search()}} className="office-form"><label>Sign-in email<input type="email" required value={email} onChange={e=>{setEmail(e.target.value);setAccounts([])}}/></label><button disabled={busy}>Find account</button></form><div className="public-records-controls"><label>New workspace<select value={industry} onChange={e=>setIndustry(e.target.value)}><option value="insurance">Insurance agency</option><option value="real-estate">Real estate</option><option value="legal">Legal / immigration</option><option value="general">General business</option></select></label><label>Duration<select value={duration} onChange={e=>setDuration(e.target.value)}><option value="permanent">Permanent · no expiry</option><option value="7">7-day trial</option><option value="14">14-day trial</option><option value="30">30-day trial</option><option value="90">90 days</option><option value="custom">Custom days</option><option value="date">Choose expiry date</option></select></label>{duration==='custom'&&<label>Days<input type="number" min={1} max={3650} value={days} onChange={e=>setDays(Number(e.target.value))}/></label>}{duration==='date'&&<label>Expires<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label>}<label>Access<select value={scope} onChange={e=>setScope(e.target.value)}><option value="full">Full CRM</option><option value="miner-only">Miner only</option><option value="read-only">View-only Miner</option></select></label></div>{accounts.map(account=><article className="office-item" key={account.id}><div><b>{account.name||account.email}</b><p>{account.email} · {account.state} · {account.scope}</p>{account.trialEndsAt&&<p>Expires {new Date(account.trialEndsAt).toLocaleString()}</p>}</div>{account.protected?<span>Protected owner</span>:account.teamMember?<span>Manage through their workspace owner</span>:<div><button disabled={busy} onClick={()=>void change(account.id,'set-access')}>Apply selected access</button><button disabled={busy} onClick={()=>void change(account.id,account.state==='paused'?'resume':'pause')}>{account.state==='paused'?'Resume':'Pause access'}</button></div>}</article>)}<p role="status">{message}</p></section>
}
