'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createVoiceQueue,type VoiceQueueContact} from '../lib/voice-queue-browser';
import {voicePilotEligible,type VoiceCallHistory} from '../lib/voice-pilot';
export type VoicePilotSnapshot={active:boolean;name:string;number:string;status:string;human:boolean;connectedAt:number|null;muted:boolean;paused:boolean};
export type VoicePilotControls={stop:()=>void;skip:()=>void;takeOver:()=>void;pause:()=>void;mute:()=>void};
function ring(){try{const context=new AudioContext(),tone=context.createOscillator(),gain=context.createGain();tone.frequency.value=740;gain.gain.value=.06;tone.connect(gain);gain.connect(context.destination);tone.start();gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.7);tone.stop(context.currentTime+.7);tone.onended=()=>void context.close()}catch{}}
export default function AiVoicePilot({leads,busy,onActive,onClose,expanded=true,onOpen,onState,onControls}:{expanded?:boolean;onOpen?:()=>void;onState?:(state:VoicePilotSnapshot)=>void;onControls?:(controls:VoicePilotControls|null)=>void;leads:Array<{id:number;name:string;phone?:string;stage?:string;outcome?:string;doNotCall?:boolean}>;busy:boolean;onActive:(active:boolean)=>void;onClose:()=>void}){
 const [scope,setScope]=useState('queue'),[leadId,setLeadId]=useState(''),[kind,setKind]=useState('all'),[timezone,setTimezone]=useState('America/Los_Angeles');
 const [active,setActive]=useState(false),[paused,setPaused]=useState(false),[loading,setLoading]=useState(false),[queueLoaded,setQueueLoaded]=useState(false),[status,setStatus]=useState(''),[transcript,setTranscript]=useState(''),[handoff,setHandoff]=useState(''),[human,setHuman]=useState(false);
 const [contacts,setContacts]=useState<VoiceQueueContact[]>([]),[excluded,setExcluded]=useState(0),[history,setHistory]=useState<VoiceCallHistory[]>([]),[maxCalls,setMaxCalls]=useState(25),[maxMinutes,setMaxMinutes]=useState(60),[progress,setProgress]=useState('');
 const [voicemail,setVoicemail]=useState<'skip'|'leave'>('skip'),[message,setMessage]=useState(''),[current,setCurrent]=useState<VoiceQueueContact|null>(null),[connectedAt,setConnectedAt]=useState<number|null>(null),[muted,setMuted]=useState(false);
 const pausedRef=useRef(false),mutedRef=useRef(false);
 const queue=useRef<ReturnType<typeof createVoiceQueue>|null>(null),activeCallback=useRef(onActive),requestSequence=useRef(0),mounted=useRef(true);
 const controls=useMemo<VoicePilotControls>(()=>({
  stop:()=>queue.current?.stop(),skip:()=>queue.current?.skip(),takeOver:()=>{void queue.current?.takeOver()},
  pause:()=>{pausedRef.current=!pausedRef.current;if(pausedRef.current)queue.current?.pause();else queue.current?.resume();setPaused(pausedRef.current)},
  mute:()=>{mutedRef.current=!mutedRef.current;queue.current?.mute(mutedRef.current);setMuted(mutedRef.current)}
 }),[]);
 useEffect(()=>{onControls?.(controls);return()=>onControls?.(null)},[onControls,controls]);
 useEffect(()=>{onState?.({active,name:current?.name||'Ava Autopilot',number:current?.phone||'',status,human,connectedAt,muted,paused})},[onState,active,current,status,human,connectedAt,muted,paused]);
 const eligibleIds=useMemo(()=>new Set(leads.filter(l=>voicePilotEligible(l)).map(l=>l.id)),[leads]);
 const ready=useMemo(()=>contacts.filter(l=>eligibleIds.has(l.id)),[contacts,eligibleIds]);
 const startIssue=busy?'Call in progress':loading?'Loading…':!queueLoaded?'Load queue':!ready.length?'No eligible contacts':scope==='single'&&!ready.some(l=>l.id===Number(leadId))?'Choose a contact':'';
 const queueStatus=queueLoaded?(ready.length?`${ready.length} ready · ${excluded+contacts.length-ready.length} skipped`:'No eligible contacts'):'';
 useEffect(()=>{activeCallback.current=onActive},[onActive]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;queue.current?.stop();activeCallback.current(false)}},[]);
 useEffect(()=>{if(busy)queue.current?.stop('Stopped for another phone call.')},[busy]);
 async function loadQueue(){setQueueLoaded(false);setContacts([]);setExcluded(0);setStatus('Loading…');const sequence=++requestSequence.current;setLoading(true);try{const r=await fetch('/api/ai/voice-call',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'queue',kind})}),data=await r.json();if(!r.ok)throw Error(data.error);if(sequence!==requestSequence.current||!mounted.current)return;setContacts(data.queue);setExcluded(data.excluded);setHistory(data.history||[]);setQueueLoaded(true);setStatus('')}catch(e){if(sequence===requestSequence.current&&mounted.current)setStatus(e instanceof Error?e.message:'Queue unavailable.')}finally{if(sequence===requestSequence.current&&mounted.current)setLoading(false)}}
 function start(){
  if(active||startIssue)return;const selected=scope==='single'?ready.filter(l=>l.id===Number(leadId)):ready.slice(0,maxCalls);if(!selected.length)return;
  setTranscript('');setHandoff('');setHuman(false);setPaused(false);pausedRef.current=false;mutedRef.current=false;setMuted(false);setActive(true);onActive(true);
  queue.current=createVoiceQueue({contacts:selected,timezone,maxMinutes,messageOptions:{voicemail,message},onConnected:setConnectedAt,onStatus:text=>{if(mounted.current)setStatus(text)},onContact:(contact,index,total)=>{setCurrent(contact);setConnectedAt(null);mutedRef.current=false;setMuted(false);setHandoff('');setHuman(false);setProgress(`${index} / ${total} · ${contact.name}`)},onTranscript:setTranscript,onHandoff:(contact,summary)=>{ring();setHandoff(`${contact.name} · ${summary||'Ready to speak with you.'}`)},onHuman:setHuman,onResult:(contact,result)=>{if(mounted.current)setHistory(list=>[{id:crypto.randomUUID(),leadId:contact.id,phone:contact.phone,startedAt:Date.now(),outcome:result.outcome,summary:result.summary},...list].slice(0,30))},onEnd:()=>{if(mounted.current){setActive(false);setPaused(false);setHuman(false)}activeCallback.current(false)}});void queue.current.start();
 }
 if(!expanded)return active?<section className="ava-dock" aria-label="Ava Autopilot controls"><button onClick={onOpen}><strong>Ava · {current?.name||'Autopilot'}</strong><small role="status">{status}</small></button><button onClick={human?controls.mute:controls.takeOver}>{human?(muted?'Unmute':'Mute'):'Take over'}</button><button onClick={controls.pause}>{paused?'Resume':'Pause'}</button><button onClick={controls.stop}>Stop</button></section>:null;
 return <div className="ava-panel"><section className="ai-voice-pilot" role="region" aria-label="AI Autopilot"><header><div><small>DIALER · AUTO + HOME</small><h2>Ava Autopilot</h2></div><button onClick={onClose} aria-label="Minimize AI Autopilot">−</button></header>
  <p role="status">{status||queueStatus}</p>{progress&&<small>{progress}</small>}{handoff&&<div className="voice-handoff" role="alert"><strong>{human?'You’re connected':'Interested caller'}</strong><p>{handoff}</p></div>}
  {!active&&<><div className="voice-pilot-grid"><label>Calling mode<select value={scope} onChange={e=>setScope(e.target.value)}><option value="queue">Continuous queue</option><option value="single">One contact</option></select></label><label>Contacts<select value={kind} onChange={e=>{requestSequence.current++;setKind(e.target.value);setContacts([]);setExcluded(0);setQueueLoaded(false);setStatus('');setLoading(false)}}><option value="all">All eligible contacts</option><option value="auto">Auto</option><option value="home">Home</option></select></label></div><div className="voice-queue-load"><button disabled={loading||busy} onClick={()=>void loadQueue()}>{loading?'Loading…':'Load queue'}</button></div>{scope==='single'&&<label>Contact<select aria-label="AI call contact" value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Choose a contact</option>{ready.map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label>}
  <div className="voice-pilot-grid"><label>Call limit<input aria-label="Call limit" type="number" min={1} max={500} value={maxCalls} onChange={e=>setMaxCalls(Math.max(1,Math.min(500,Number(e.target.value)||1)))}/></label><label>Session minutes<input aria-label="Session minutes" type="number" min={5} max={120} value={maxMinutes} onChange={e=>setMaxMinutes(Math.max(5,Math.min(120,Number(e.target.value)||5)))}/></label></div>
  <label>Voicemail<select aria-label="Voicemail" value={voicemail} onChange={e=>setVoicemail(e.target.value as 'skip'|'leave')}><option value="skip">Skip voicemail</option><option value="leave">Leave a message with Ava</option></select></label>{voicemail==='leave'&&<label>Message<textarea aria-label="Voicemail message" maxLength={400} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ava introduces your agency and leaves your CRM phone number."/></label>}
  <label>Recipient time zone<select value={timezone} onChange={e=>setTimezone(e.target.value)}>{['America/Los_Angeles','America/Denver','America/Chicago','America/New_York','America/Phoenix','America/Anchorage','Pacific/Honolulu'].map(zone=><option key={zone}>{zone}</option>)}</select></label></>}
  <div className="voice-pilot-actions">{active?<><button className="primary" onClick={human?controls.mute:controls.takeOver}>{human?(muted?'Unmute':'Mute'):'Take over'}</button><button onClick={controls.pause}>{paused?'Resume queue':'Pause after call'}</button><button disabled={!connectedAt} onClick={controls.skip}>Skip contact</button><button className="danger" onClick={controls.stop}>Stop Autopilot</button></>:<button className="primary" title={startIssue||undefined} disabled={Boolean(startIssue)} onClick={start}>Start Autopilot</button>}</div>
  <small>Keep Pacifica open · You can switch pages</small>
  {transcript&&<details open><summary>Live transcript</summary><pre>{transcript}</pre><button onClick={()=>void navigator.clipboard.writeText(transcript)}>Copy transcript</button></details>}
  {history.length>0&&<details><summary>Recent results · {history.length}</summary>{history.slice(0,15).map(h=><p key={h.id}><strong>{leads.find(l=>l.id===h.leadId)?.name||h.phone}</strong> · {h.outcome.replaceAll('-',' ')}{h.summary&&<small>{h.summary}</small>}</p>)}</details>}
 </section></div>;
}
