'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createVoiceQueue,type VoiceQueueContact} from '../lib/voice-queue-browser';
import {voicePilotEligible,type VoiceCallHistory} from '../lib/voice-pilot';
function ring(){try{const context=new AudioContext(),tone=context.createOscillator(),gain=context.createGain();tone.frequency.value=740;gain.gain.value=.06;tone.connect(gain);gain.connect(context.destination);tone.start();gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.7);tone.stop(context.currentTime+.7);tone.onended=()=>void context.close()}catch{}}
export default function AiVoicePilot({leads,busy,onActive,onClose}:{leads:Array<{id:number;name:string;phone?:string;stage?:string;outcome?:string;doNotCall?:boolean}>;busy:boolean;onActive:(active:boolean)=>void;onClose:()=>void}){
 const [scope,setScope]=useState('queue'),[leadId,setLeadId]=useState(''),[kind,setKind]=useState('all'),[timezone,setTimezone]=useState('America/Los_Angeles');
 const [active,setActive]=useState(false),[paused,setPaused]=useState(false),[loading,setLoading]=useState(false),[queueLoaded,setQueueLoaded]=useState(false),[status,setStatus]=useState(''),[transcript,setTranscript]=useState(''),[handoff,setHandoff]=useState(''),[human,setHuman]=useState(false);
 const [contacts,setContacts]=useState<VoiceQueueContact[]>([]),[excluded,setExcluded]=useState(0),[history,setHistory]=useState<VoiceCallHistory[]>([]),[maxCalls,setMaxCalls]=useState(25),[maxMinutes,setMaxMinutes]=useState(60),[progress,setProgress]=useState('');
 const queue=useRef<ReturnType<typeof createVoiceQueue>|null>(null),activeCallback=useRef(onActive),requestSequence=useRef(0),mounted=useRef(true);
 const eligibleIds=useMemo(()=>new Set(leads.filter(l=>voicePilotEligible(l)).map(l=>l.id)),[leads]);
 const ready=useMemo(()=>contacts.filter(l=>eligibleIds.has(l.id)),[contacts,eligibleIds]);
 const startIssue=busy?'Call in progress':loading?'Loading…':!queueLoaded?'Load queue':!ready.length?'No eligible contacts':scope==='single'&&!ready.some(l=>l.id===Number(leadId))?'Choose a contact':'';
 const queueStatus=queueLoaded?(ready.length?`${ready.length} ready · ${excluded+contacts.length-ready.length} skipped`:'No eligible contacts'):'';
 useEffect(()=>{activeCallback.current=onActive},[onActive]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;queue.current?.stop();activeCallback.current(false)}},[]);
 useEffect(()=>{if(busy)queue.current?.stop('Stopped for another phone call.')},[busy]);
 async function loadQueue(){setQueueLoaded(false);setContacts([]);setExcluded(0);setStatus('Loading…');const sequence=++requestSequence.current;setLoading(true);try{const r=await fetch('/api/ai/voice-call',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'queue',kind})}),data=await r.json();if(!r.ok)throw Error(data.error);if(sequence!==requestSequence.current||!mounted.current)return;setContacts(data.queue);setExcluded(data.excluded);setHistory(data.history||[]);setQueueLoaded(true);setStatus('')}catch(e){if(sequence===requestSequence.current&&mounted.current)setStatus(e instanceof Error?e.message:'Queue unavailable.')}finally{if(sequence===requestSequence.current&&mounted.current)setLoading(false)}}
 function start(){
  if(active||startIssue)return;const selected=scope==='single'?ready.filter(l=>l.id===Number(leadId)):ready.slice(0,maxCalls);if(!selected.length)return;
  setTranscript('');setHandoff('');setHuman(false);setPaused(false);setActive(true);onActive(true);
  queue.current=createVoiceQueue({contacts:selected,timezone,maxMinutes,onStatus:text=>{if(mounted.current)setStatus(text)},onContact:(contact,index,total)=>{setHandoff('');setHuman(false);setProgress(`${index} / ${total} · ${contact.name}`)},onTranscript:setTranscript,onHandoff:(contact,summary)=>{ring();setHandoff(`${contact.name} · ${summary||'Ready to speak with you.'}`)},onHuman:setHuman,onResult:(contact,result)=>{if(mounted.current)setHistory(list=>[{id:crypto.randomUUID(),leadId:contact.id,phone:contact.phone,startedAt:Date.now(),outcome:result.outcome,summary:result.summary},...list].slice(0,30))},onEnd:()=>{if(mounted.current){setActive(false);setPaused(false);setHuman(false)}activeCallback.current(false)}});void queue.current.start();
 }
 return <div className="drawer-backdrop"><section className="ai-voice-pilot" role="dialog" aria-modal="true" aria-label="AI Autopilot"><header><div><small>AUTO + HOME</small><h2>AI Autopilot</h2></div><button onClick={onClose} aria-label="Close AI Autopilot">×</button></header>
  <p role="status">{status||queueStatus}</p>{progress&&<small>{progress}</small>}{handoff&&<div className="voice-handoff" role="alert"><strong>{human?'You’re connected':'Interested caller'}</strong><p>{handoff}</p></div>}
  {!active&&<><div className="voice-pilot-grid"><label>Calling mode<select value={scope} onChange={e=>setScope(e.target.value)}><option value="queue">Continuous queue</option><option value="single">One contact</option></select></label><label>Contacts<select value={kind} onChange={e=>{requestSequence.current++;setKind(e.target.value);setContacts([]);setExcluded(0);setQueueLoaded(false);setStatus('');setLoading(false)}}><option value="all">All eligible contacts</option><option value="auto">Auto</option><option value="home">Home</option></select></label></div><div className="voice-queue-load"><button disabled={loading||busy} onClick={()=>void loadQueue()}>{loading?'Loading…':'Load queue'}</button></div>{scope==='single'&&<label>Contact<select aria-label="AI call contact" value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Choose a contact</option>{ready.map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label>}
  <div className="voice-pilot-grid"><label>Call limit<input aria-label="Call limit" type="number" min={1} max={500} value={maxCalls} onChange={e=>setMaxCalls(Math.max(1,Math.min(500,Number(e.target.value)||1)))}/></label><label>Session minutes<input aria-label="Session minutes" type="number" min={5} max={120} value={maxMinutes} onChange={e=>setMaxMinutes(Math.max(5,Math.min(120,Number(e.target.value)||5)))}/></label></div>
  <label>Recipient time zone<select value={timezone} onChange={e=>setTimezone(e.target.value)}>{['America/Los_Angeles','America/Denver','America/Chicago','America/New_York','America/Phoenix','America/Anchorage','Pacific/Honolulu'].map(zone=><option key={zone}>{zone}</option>)}</select></label></>}
  <div className="voice-pilot-actions">{active?<><button className="primary" disabled={human} onClick={()=>void queue.current?.takeOver()}>Take over</button><button onClick={()=>{if(paused)queue.current?.resume();else queue.current?.pause();setPaused(!paused)}}>{paused?'Resume queue':'Pause after call'}</button><button className="danger" onClick={()=>queue.current?.stop()}>Stop Autopilot</button></>:<button className="primary" title={startIssue||undefined} disabled={Boolean(startIssue)} onClick={start}>Start Autopilot</button>}</div>
  <small>Headset ready · Keep Pacifica open</small>
  {transcript&&<details open><summary>Live transcript</summary><pre>{transcript}</pre><button onClick={()=>void navigator.clipboard.writeText(transcript)}>Copy transcript</button></details>}
  {history.length>0&&<details><summary>Recent results · {history.length}</summary>{history.slice(0,15).map(h=><p key={h.id}><strong>{leads.find(l=>l.id===h.leadId)?.name||h.phone}</strong> · {h.outcome.replaceAll('-',' ')}{h.summary&&<small>{h.summary}</small>}</p>)}</details>}
 </section></div>;
}
