'use client';
import {useEffect,useRef,useState} from 'react';
import {createVoicePilot} from '../lib/voice-pilot-browser';
import {voicePilotEligible} from '../lib/voice-pilot';
export default function AiVoicePilot({leads,busy,onActive,onClose}:{leads:Array<{id:number;name:string;phone?:string;stage?:string;outcome?:string;doNotCall?:boolean}>;busy:boolean;onActive:(active:boolean)=>void;onClose:()=>void}){
 const [leadId,setLeadId]=useState(''),[evidence,setEvidence]=useState(''),[confirmed,setConfirmed]=useState(false),[timezone,setTimezone]=useState('America/Los_Angeles'),[active,setActive]=useState(false),[status,setStatus]=useState('One supervised call. Keep Pacifica open.'),[transcript,setTranscript]=useState('');
 const pilot=useRef<ReturnType<typeof createVoicePilot>|null>(null),activeCallback=useRef(onActive);
 useEffect(()=>{activeCallback.current=onActive},[onActive]);
 useEffect(()=>()=>{pilot.current?.stop();activeCallback.current(false)},[]);
 useEffect(()=>{if(busy)pilot.current?.stop('Stopped for another phone call.')},[busy]);
 function start(){if(active||busy)return;setTranscript('');setActive(true);onActive(true);pilot.current=createVoicePilot({leadId:Number(leadId),permissionEvidence:evidence,timezone,onStatus:setStatus,onTranscript:setTranscript,onEnd:()=>{setActive(false);activeCallback.current(false)}});void pilot.current.start()}
 return <div className="drawer-backdrop"><section className="ai-voice-pilot" role="dialog" aria-modal="true" aria-label="AI Autopilot"><header><div><small>INSURANCE · FIRST CALL</small><h2>AI Autopilot</h2></div><button onClick={onClose} aria-label="Close AI Autopilot">×</button></header><p role="status">{status}</p><label>Contact<select aria-label="AI call contact" disabled={active} value={leadId} onChange={e=>{setLeadId(e.target.value);setConfirmed(false);setEvidence('')}}><option value="">Choose a saved contact</option>{leads.filter(l=>voicePilotEligible(l)).map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label><label>Recipient time zone<select disabled={active} value={timezone} onChange={e=>setTimezone(e.target.value)}>{['America/Los_Angeles','America/Denver','America/Chicago','America/New_York','America/Phoenix','America/Anchorage','Pacific/Honolulu'].map(zone=><option key={zone}>{zone}</option>)}</select></label><label>Written AI-call permission<input aria-label="AI call permission evidence" disabled={active} value={evidence} onChange={e=>setEvidence(e.target.value)} maxLength={1000} placeholder="Source, date, and record of permission"/></label><label className="voice-pilot-permission"><input type="checkbox" disabled={active} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified written permission for AI voice calls and this recipient’s time zone.</label><div className="voice-pilot-actions">{active?<><button className="primary" onClick={()=>void pilot.current?.takeOver()}>Take over</button><button className="danger" onClick={()=>pilot.current?.stop()}>Stop AI call</button></>:<button className="primary" disabled={busy||!leadId||!confirmed||evidence.trim().length<12} onClick={start}>Start AI call</button>}</div><small>Ava identifies herself as AI. Calls stop on disconnect and after five minutes. Start each call yourself.</small>{transcript&&<details open><summary>Call transcript</summary><pre>{transcript}</pre><button onClick={()=>void navigator.clipboard.writeText(transcript)}>Copy transcript</button></details>}</section></div>;
}
