'use client';
import {useCallback,useEffect,useState} from 'react';
import {desktopNotifications} from '../lib/desktop-notifications';
type Connection={configured:boolean;canManage:boolean;connected:boolean;lastSyncAt:string;pending:number;error:string;calendarUrl:string;showExternal?:boolean;canReadExternal?:boolean};
function ProviderConnection({provider}:{provider:'google'|'outlook'}){
 const name=provider==='google'?'Google':'Outlook';const [status,setStatus]=useState<Connection|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await fetch(`/api/calendar/${provider}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setStatus(d)},[provider]);
 useEffect(()=>{let active=true;const refresh=()=>{if(active)void load().catch(()=>{if(active)setMessage('Connection could not load.')})};const timer=setTimeout(refresh,0);window.addEventListener('pacifica:calendar-synced',refresh);return()=>{active=false;clearTimeout(timer);window.removeEventListener('pacifica:calendar-synced',refresh)}},[load]);
 async function action(value:string,showExternal?:boolean){
 if(value==='connect'&&desktopNotifications()?.isDesktop){try{await desktopNotifications()?.openCalendarBrowser?.();setMessage(`Connect ${name} in Calendar settings in your browser, then return here.`)}catch{setMessage('Open pacificacrm.com/dashboard in your browser to connect.')}return}
 if(value==='disconnect'&&!window.confirm(`Disconnect ${name}? Existing synced events remain in ${name}.`))return;
 setBusy(true);setMessage('');try{const r=await fetch(`/api/calendar/${provider}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:value,showExternal})}),d=await r.json();if(!r.ok)throw Error(d.error);if(d.url){window.location.assign(d.url);return}await load();window.dispatchEvent(new Event('pacifica:external-calendar-changed'));setMessage(value==='disconnect'?'Disconnected. Existing events remain.':value==='preferences'?'Calendar display updated.':d.pending?`${d.pending} changes waiting to sync.`:`${name} Calendar is up to date.`)}catch(e){setMessage(e instanceof Error?e.message:'Calendar action failed.')}finally{setBusy(false)}}
 return <section className="calendar-connection"><h3>{name} Calendar</h3><p>Sync CRM appointments and payments to a separate Pacifica CRM calendar.</p><p>{status?.connected?'Connected':status?.configured?'Ready to connect':status?'Administrator setup needed':'Checking…'}</p>{status?.canManage&&status.configured&&<div className="calendar-actions"><button disabled={busy} onClick={()=>void action('connect')}>{status.connected?`Reconnect ${name}`:`Connect ${name} Calendar`}</button>{status.connected&&<><button disabled={busy} onClick={()=>void action('sync')}>Sync {name} now</button><button disabled={busy} onClick={()=>void action('disconnect')}>Disconnect {name}</button></>}</div>}{status?.connected&&status.canManage&&<label><input type="checkbox" checked={Boolean(status.showExternal)} disabled={busy} onChange={e=>void action('preferences',e.target.checked)}/> Show my {name} primary calendar to this workspace</label>}{status?.connected&&<small>Outside events are read-only here. Changes to CRM events are made in Pacifica. No invitations are sent.</small>}{status?.lastSyncAt&&<small>Last synced {new Date(status.lastSyncAt).toLocaleString()}</small>}{status?.calendarUrl&&<a href={status.calendarUrl} target="_blank" rel="noreferrer">Open {name} Calendar ↗</a>}<p role="status">{message||status?.error}</p></section>;
}
function CalendarSubscription(){
 const [status,setStatus]=useState<{configured:boolean;canManage:boolean;connected:boolean;url:string}|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const load=useCallback(async()=>{const r=await fetch('/api/calendar/feed',{cache:'no-store'});if(r.ok)setStatus(await r.json())},[]);useEffect(()=>{void load().catch(()=>setMessage('Subscription status unavailable.'))},[load]);
 async function action(action:string){setBusy(true);try{const r=await fetch('/api/calendar/feed',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}),d=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage(action==='disconnect'?'Subscription revoked.':'Copy this private URL into your calendar’s subscription settings.')}catch(e){setMessage(e instanceof Error?e.message:'Subscription failed.')}finally{setBusy(false)}}
 return <section className="calendar-connection"><h3>Apple Calendar & other calendar apps</h3><p>A private, read-only subscription to your CRM events. Refresh timing is controlled by your calendar app.</p>{status?.canManage&&status.configured&&<button disabled={busy} onClick={()=>void action(status.connected?'disconnect':'connect')}>{status.connected?'Revoke subscription':'Create private subscription'}</button>}{status?.url&&<label>Private calendar URL (anyone with this URL can view these events)<input readOnly value={status.url} onFocus={e=>e.target.select()}/></label>}{status&&!status.configured&&<p>Administrator encryption setup needed.</p>}<p role="status">{message}</p></section>;
}
export default function CalendarConnection(){const [failed,setFailed]=useState(false);useEffect(()=>{if(new URLSearchParams(window.location.search).get('calendar')==='failed')queueMicrotask(()=>setFailed(true))},[]);return <>{failed&&<p role="status">Calendar authorization was not completed. Try Connect or Reconnect when ready.</p>}<ProviderConnection provider="google"/><ProviderConnection provider="outlook"/><CalendarSubscription/></>}
