'use client';
import {useEffect,useRef,useState} from 'react';
export type PageContext={title:string;url:string;text:string};
type PageState={url:string;title:string;loading:boolean;error:string;canGoBack:boolean;canGoForward:boolean};
type PageBridge={open:(url:string,workspaceId:string)=>Promise<PageState>;bounds:(value:{bounds:{x:number;y:number;width:number;height:number};visible:boolean})=>Promise<unknown>;action:(name:string)=>Promise<PageState>;capture:()=>Promise<PageContext>;close:()=>Promise<unknown>;onState:(listener:(state:PageState)=>void)=>()=>void};
const empty:PageState={url:'',title:'',loading:false,error:'',canGoBack:false,canGoForward:false};
function desktopBrowser(){return typeof window==='undefined'?undefined:(window as unknown as {pacificaDesktop?:{connectedBrowser?:PageBridge}}).pacificaDesktop?.connectedBrowser}
function safeUrl(value:string){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:''}catch{return ''}}
export default function ConnectedPages({workspaceId,onClose,onAdd,onNavigate}:{workspaceId:string;onClose:()=>void;onAdd:(context:PageContext)=>void;onNavigate?:(view:'messages'|'office'|'settings')=>void}){
 const native=desktopBrowser(),viewport=useRef<HTMLDivElement>(null),addressInput=useRef<HTMLInputElement>(null),alive=useRef(true);
 const [address,setAddress]=useState(''),[state,setState]=useState<PageState>(empty),[paste,setPaste]=useState(''),[showPaste,setShowPaste]=useState(!native),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{alive.current=true;addressInput.current?.focus();const unsubscribe=native?.onState(next=>{setState(next);if(next.url)setAddress(next.url)});const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',escape);return()=>{alive.current=false;unsubscribe?.();window.removeEventListener('keydown',escape);void native?.close().catch(()=>{})}},[native,onClose]);
 useEffect(()=>{
  if(!native||!viewport.current)return;let frame=0;
  const sync=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const box=viewport.current?.getBoundingClientRect();if(!box)return;const obscured=Boolean(document.querySelector('.drawer-backdrop,.incoming-call-backdrop,.new-lead-backdrop,.post-call-modal,[role="dialog"][aria-modal="true"],dialog[open]'));void native.bounds({bounds:{x:box.x,y:box.y,width:box.width,height:box.height},visible:!obscured&&document.visibilityState==='visible'&&Boolean(state.url)&&!showPaste}).catch(()=>{})})};
  const resize=new ResizeObserver(sync);resize.observe(viewport.current);const modal=new MutationObserver(sync);modal.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','open','aria-modal']});window.addEventListener('resize',sync);document.addEventListener('visibilitychange',sync);sync();return()=>{cancelAnimationFrame(frame);resize.disconnect();modal.disconnect();window.removeEventListener('resize',sync);document.removeEventListener('visibilitychange',sync)};
 },[native,state.url,showPaste]);
 async function work(task:()=>Promise<void>){if(busy)return;setBusy(true);setNotice('');try{await task()}catch(e){if(alive.current)setNotice(e instanceof Error?e.message:'Try again or open the site in your browser.')}finally{if(alive.current)setBusy(false)}}
 function add(context:PageContext){onAdd(context);setNotice('Page context added to this AI conversation.');setPaste('')}
 const href=safeUrl(address);
 return <aside className="connected-pages" aria-label="Connected pages"><header><div><span>WORKSPACE</span><h2>Pages & connections</h2></div><button type="button" aria-label="Close connected pages" onClick={onClose}>×</button></header>
  {onNavigate&&<nav aria-label="Connected CRM tools"><button onClick={()=>onNavigate('messages')}>Messages</button><button onClick={()=>onNavigate('office')}>Calendar</button><button onClick={()=>onNavigate('settings')}>Integrations</button></nav>}
  <form className="connected-address" onSubmit={event=>{event.preventDefault();if(native&&href)void work(async()=>{const next=await native.open(href,workspaceId);if(alive.current){setState(next);setShowPaste(false)}})}}><input ref={addressInput} type="url" aria-label="Website address" placeholder="https://your-website.com" value={address} onChange={event=>setAddress(event.target.value)}/>{native?<button disabled={!href||busy}>Open</button>:<a href={href||undefined} aria-disabled={!href} target="_blank" rel="noreferrer">Open ↗</a>}</form>
  {native&&<div className="connected-browser-tools"><button disabled={!state.canGoBack} aria-label="Previous page" onClick={()=>void work(async()=>setState(await native.action('back')))}>←</button><button disabled={!state.canGoForward} aria-label="Next page" onClick={()=>void work(async()=>setState(await native.action('forward')))}>→</button><button disabled={!state.url} aria-label="Reload page" onClick={()=>void work(async()=>setState(await native.action('reload')))}>↻</button><span>{state.loading?'Loading…':state.title||'Your connected page'}</span><a href={safeUrl(state.url)||href||undefined} target="_blank" rel="noreferrer">Open in browser ↗</a></div>}
  {(notice||state.error)&&<p className="connected-notice" role="status">{notice||state.error}</p>}
  <div className="connected-page-viewport" ref={viewport}>{showPaste?<div className="connected-paste"><h3>Bring the details into AI.</h3><p>{native?'Paste any additional page text here.':'Open a site in your browser, then paste the details you want AI to read.'}</p><textarea aria-label="Page text to share with AI" value={paste} maxLength={24000} onChange={event=>setPaste(event.target.value)} placeholder="Paste page text…"/><button disabled={!paste.trim()} onClick={()=>add({title:href?new URL(href).hostname:'Pasted page',url:href,text:paste})}>Add text to AI</button></div>:!state.url?<div className="connected-page-empty"><span aria-hidden="true">↗</span><h3>A little more context.</h3><p>Open a website alongside Pacifica. Sign in there, then add the page when you want AI to read it.</p></div>:null}</div>
  <footer>{native&&<><button className="primary" disabled={!state.url||state.loading||busy||showPaste} onClick={()=>void work(async()=>add(await native.capture()))}>Add page to AI</button><button onClick={()=>setShowPaste(value=>!value)}>{showPaste?'Back to page':'Paste text'}</button><button disabled={!state.url} onClick={()=>void work(async()=>{setState(await native.action('disconnect'));setAddress('');setNotice('Page session signed out.')})}>Sign out</button></>}{!native&&<small>Embedded pages are available in the updated Pacifica desktop app.</small>}</footer>
 </aside>;
}
