'use client';
import {useState} from 'react';
import {contractorRenewals,contractorCsv,cslbPortal,type ContractorRenewal} from '../lib/contractor-renewals';
export default function ContractorRenewals({onImport}:{onImport:(file:File)=>void}){
 const [file,setFile]=useState<File|null>(null),[snapshot,setSnapshot]=useState(''),[counties,setCounties]=useState('Los Angeles, Ventura'),[classes,setClasses]=useState(''),[days,setDays]=useState(120),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[items,setItems]=useState<ContractorRenewal[]>([]);
 const clear=()=>{setItems([]);setMessage('')};
 async function review(){if(!file||busy)return;setBusy(true);setItems([]);setMessage('Reading the license and insurance fields…');try{if(file.size>120*1024*1024)throw Error('Choose a CSV smaller than 120 MB.');const result=await contractorRenewals(await file.text(),{counties,classes,days,snapshot});setItems(result.items);setMessage(`${result.eligible.toLocaleString()} matching licenses with business phones · showing the nearest ${result.items.length} renewals. ${result.scanned.toLocaleString()} rows checked.`)}catch(e){setMessage(e instanceof Error?e.message:'Could not read the CSV.')}finally{setBusy(false)}}
 return <details className="miner-engine-card" style={{padding:20,fontSize:13,lineHeight:1.6}}><summary>Contractor renewal prospects · CSLB</summary><p>Import the <a href={cslbPortal} target="_blank" rel="noreferrer">CSLB License Master CSV</a> to find recorded workers’ compensation expirations. Preview up to 100 businesses at a time. These are prospects; interest and current coverage still need confirmation.</p><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><div className="miner-config-grid"><label className="miner-field"><span>License Master CSV</span><input type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]||null);clear()}}/></label><label className="miner-field"><span>CSLB source date</span><input type="date" value={snapshot} onChange={e=>{setSnapshot(e.target.value);clear()}}/></label><label className="miner-field"><span>Counties</span><input value={counties} onChange={e=>{setCounties(e.target.value);clear()}} placeholder="Los Angeles, Ventura"/></label><label className="miner-field"><span>Class codes (optional)</span><input value={classes} onChange={e=>{setClasses(e.target.value);clear()}} placeholder="B, C10, C20, C36, C39"/></label><label className="miner-field"><span>Insurance expires within</span><select value={days} onChange={e=>{setDays(Number(e.target.value));clear()}}>{[30,60,90,120].map(n=><option key={n} value={n}>{n} days</option>)}</select></label></div><button disabled={!file||!snapshot||busy} onClick={()=>void review()}>{busy?'Reading…':'Preview renewal prospects'}</button></fieldset><p role="status">{message}</p>{items.length>0&&<><ul>{items.slice(0,8).map(item=><li key={item.license}><b>{item.name}</b> · {item.expiration} · {item.days} days · {item.county} · {item.classes}</li>)}</ul><button className="primary" onClick={()=>{onImport(new File([contractorCsv(items)],'CSLB-renewal-prospects.csv',{type:'text/csv'}));setItems([]);setMessage('Sent to the existing CRM import. Duplicate contacts are merged; no messages are sent.')}}>Import {items.length} prospects</button></>}</details>;
}
