'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {kindLabel,leadKinds,minerSources,cleanMinerState,type LeadKind,type MinerSource,type MinerState,type SourceProspect} from '../lib/miner-leads';
import type {MinerInsight} from '../lib/miner-prospect-tools';
type Prospect={id:number;name:string;phone?:string;email?:string;source:string;product?:string;address?:string;zip?:string;extraFields?:Record<string,string>};
type Snapshot=MinerState&{prospects:Prospect[];scheduleConfigured?:boolean;checkedAt?:number};
const empty:Snapshot={campaigns:[],inquiries:[],searches:[],prospects:[]};
async function api(path:string,body?:unknown){const response=await fetch(`/api/miner/${path}`,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to complete this request.');return data;}
export default function MinerStudio({readOnly=false,initialKind='commercial',onProspects,onOpen}:{readOnly?:boolean;initialKind?:LeadKind;onProspects?:(items:unknown[])=>void;onOpen?:(id:number)=>void}){
 const [snapshot,setSnapshot]=useState<Snapshot>(empty),[kind,setKind]=useState<LeadKind>(initialKind),[tab,setTab]=useState<'discover'|'requests'|'prospects'>('discover');
 const [source,setSource]=useState<MinerSource>(initialKind==='home'?'parcels':initialKind==='real-estate'?'parcels':initialKind==='auto'?'businesses':'city'),[zip,setZip]=useState(''),[page,setPage]=useState(0);
 const [found,setFound]=useState<{records:SourceProspect[];hasMore:boolean}|null>(null),[selected,setSelected]=useState<string[]>([]),[insights,setInsights]=useState<MinerInsight[]>([]),[csv,setCsv]=useState('');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[name,setName]=useState(''),[link,setLink]=useState(''),[autoImport,setAutoImport]=useState(true),[filter,setFilter]=useState('');
 const [loaded,setLoaded]=useState(false);const onResults=useRef(onProspects);useEffect(()=>{onResults.current=onProspects},[onProspects]);
 const refresh=useCallback(async()=>{const data=await api('campaigns');setSnapshot({...cleanMinerState(data),prospects:data.prospects||[],scheduleConfigured:data.scheduleConfigured,checkedAt:data.checkedAt});setLoaded(true);onResults.current?.(data.prospects||[]);},[]);
 useEffect(()=>{let active=true;const load=()=>{if(active)void refresh().catch(e=>{if(active)setMessage(e.message)})};load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer)};},[refresh]);
 async function work(task:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await task()}catch(e){setMessage(e instanceof Error?e.message:'Could not complete the request.')}finally{setBusy(false)}}
 function resetResults(){setFound(null);setSelected([]);setInsights([]);setCsv('');setPage(0)}
 function chooseKind(next:LeadKind){setKind(next);setSource(minerSources.find(s=>s.kinds.includes(next))!.id);resetResults();setLink('')}
 async function search(nextPage=0){await work(async()=>{const result=await api('prospects',{action:'search',kind,source,zip,page:nextPage});setFound(result);setPage(nextPage);setCsv('');setSelected([]);setInsights([]);setMessage(result.records.length?'Choose records to research or add.':'No matching records in this source and ZIP. Try another source or use a request form.');})}
 async function importSelected(){await work(async()=>{const result=await api('prospects',{action:csv?'csv-import':'import',kind,source,zip,page,keys:selected,...(csv?{csv}:{})});await refresh();setSelected([]);setMessage(`${result.added} new prospects added; ${result.skipped} duplicates or capacity skips. Existing contacts were preserved. ${result.researchNotice||''}`);})}
 async function analyze(){await work(async()=>{if(csv)throw Error('Add these CSV prospects, then use Today to review their information.');if(selected.length>10)throw Error('Select up to 10 records for each AI review.');const data=await api('prospects',{action:'analyze',kind,source,zip,page,keys:selected});setInsights(data.insights);setMessage(data.insights.length?'AI research is ready below. Verify suggestions before acting.':'No evidence-backed research was returned for these records.');})}
 async function campaignAction(action:string,id:string){await work(async()=>{const data=await api('campaigns',{action,id});if(data.path){setLink(new URL(data.path,window.location.origin).href);setMessage('Your shareable request link is ready.')}else{await refresh();setMessage(action==='import'?'New lead added.':action==='revoke'?'Form closed. Previously submitted requests are retained.':'Request dismissed.')}})}
 async function searchAction(action:string,id?:string,enabled?:boolean){await work(async()=>{const data=await api('prospects',{action,id,enabled,kind,source,zip});await refresh();setMessage(action==='run-search'?data.message||`${data.added} new prospects added.`:action==='save-search'?'Search saved. It will run daily once the server schedule is active.':'Saved search updated.');})}
 const requests=snapshot.inquiries.filter(i=>i.kind===kind&&i.status!=='dismissed').slice().reverse(),campaigns=snapshot.campaigns.filter(c=>c.kind===kind);
 const prospects=snapshot.prospects.filter(p=>(p.extraFields?.['Inquiry category']===kind||!p.extraFields?.['Inquiry category']&&(kind==='auto'?/personal auto/i.test(p.source):p.source.toLowerCase().endsWith(kindLabel[kind].toLowerCase())))&&[p.name,p.phone,p.email,p.address].some(v=>v?.toLowerCase().includes(filter.toLowerCase())));
 return <section className="miner-studio"><header className="miner-studio-header"><div><span className="eyebrow">PACIFICA MINER</span><h1>Create your next opportunity.</h1><p>Discover prospects, collect your own customer requests, and research the details with AI.</p></div><button disabled={busy} onClick={()=>void work(refresh)}>Refresh</button></header>
  {readOnly&&<p className="miner-notice">View-only access · you can browse prospects and research sources.</p>}
  <div className="miner-kind-tabs" aria-label="Lead category">{leadKinds.map(k=><button key={k} className={kind===k?'active':''} aria-pressed={kind===k} onClick={()=>chooseKind(k)} disabled={busy}>{kindLabel[k]}</button>)}</div>
  <nav className="miner-studio-nav" aria-label="Miner sections"><button className={tab==='discover'?'active':''} onClick={()=>setTab('discover')}>Discover</button><button className={tab==='requests'?'active':''} onClick={()=>setTab('requests')}>Request forms · {requests.length}</button><button className={tab==='prospects'?'active':''} onClick={()=>setTab('prospects')}>My prospects · {prospects.length}</button></nav>
  <p role="status" aria-live="polite">{busy?'Working…':message||(!loaded?'Loading workspace…':'')}</p>
  {tab==='discover'&&<><article className="miner-card"><h2>Find {kindLabel[kind].toLowerCase()} prospects</h2><form className="miner-controls" onSubmit={e=>{e.preventDefault();void search()}}><label>Source<select value={source} onChange={e=>{setSource(e.target.value as MinerSource);resetResults()}} disabled={busy}>{minerSources.filter(s=>s.kinds.includes(kind)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>ZIP code<input value={zip} onChange={e=>{setZip(e.target.value);resetResults()}} pattern="[0-9]{5}" maxLength={5} required inputMode="numeric" placeholder="91401" disabled={busy}/></label><button className="primary" disabled={busy}>Search source</button>{!readOnly&&<button type="button" disabled={busy||!/^\d{5}$/.test(zip)} onClick={()=>void searchAction('save-search')}>Save daily search</button>}</form><p className="miner-fine">{minerSources.find(s=>s.id===source)?.detail}</p>{kind==='auto'&&<p className="miner-notice">To collect drivers who want a quote, create an Auto request form. Business discovery finds potential referral partners.</p>}
   {!readOnly&&<label className="miner-csv">Have your own list? Preview a CSV<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void work(async()=>{if(file.size>2000000)throw Error('Choose a CSV smaller than 2 MB.');const text=await file.text(),data=await api('prospects',{action:'csv-preview',kind,csv:text});setCsv(text);setFound(data);setSelected([]);setInsights([]);setPage(0);setMessage(`${data.records.length} rows ready to review. Select up to 50 per import.`);});}}/><small>Name/business name, phone, email, address, city and ZIP columns. Up to 2,000 rows. You choose which records to add.</small></label>}
   {found&&<><div className="miner-controls"><span>{found.records.length} records · {selected.length} selected</span><button disabled={busy||!selected.length||Boolean(csv)} onClick={()=>void analyze()}>Research with AI</button>{!readOnly&&<button className="primary" disabled={busy||!selected.length} onClick={()=>void importSelected()}>Add new prospects</button>}</div><div className="miner-table-scroll"><table className="miner-table"><thead><tr><th><input type="checkbox" aria-label="Select up to 50 records" checked={Boolean(selected.length)&&selected.length===Math.min(50,found.records.length)} onChange={e=>setSelected(e.target.checked?found.records.slice(0,50).map(r=>r.key):[])} disabled={busy}/></th><th>Prospect</th><th>Details</th><th>Contact</th></tr></thead><tbody>{found.records.map((r,index)=><tr key={`${r.key}:${index}`}><td><input type="checkbox" aria-label={`Select ${r.name}`} checked={selected.includes(r.key)} disabled={busy||selected.length>=50&&!selected.includes(r.key)} onChange={e=>setSelected(list=>e.target.checked?[...list,r.key]:list.filter(k=>k!==r.key))}/></td><td><b>{r.name}</b><small>{r.address} {r.city} {r.zip}</small>{r.url&&<a href={r.url} target="_blank" rel="noreferrer">Source record</a>}</td><td>{r.fields['Industry']||r.fields['Property use']||r.fields.lictype||r.fields.category||r.source}<small>{r.fields['Record type']||'Public prospect · interest unconfirmed'}</small></td><td>{r.phone||r.email||'Contact research needed'}</td></tr>)}</tbody></table></div>{!csv&&<div className="miner-controls"><button disabled={busy||page===0} onClick={()=>void search(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={busy||!found.hasMore} onClick={()=>void search(page+1)}>Next</button></div>}</>}
   {insights.length>0&&<div className="miner-research"><h3>AI research · verify before acting</h3>{insights.map(i=><article key={i.key}><b>{found?.records.find(r=>r.key===i.key)?.name}</b><p>{i.summary}</p><p>{i.nextStep}</p><small>Source evidence: “{i.evidence}”</small></article>)}</div>}
  </article><article className="miner-card"><h2>Daily discovery</h2><p>Each saved search checks the next page and adds only new records. Connected AI adds research to up to 10 new prospects per batch. It never changes an existing contact.</p>{snapshot.scheduleConfigured===false&&<p className="miner-notice">Automatic runs need the site’s scheduled Miner job connected. You can use Run now in the meantime.</p>}{snapshot.searches.filter(s=>s.kind===kind).map(s=><div className="miner-saved-search" key={s.id}><div><b>{minerSources.find(source=>source.id===s.source)?.name} · {s.zip}</b><small>{s.enabled?'Daily':'Paused'} · {s.lastStatus}{s.lastRunAt?` · ${new Date(s.lastRunAt).toLocaleString()}`:''}</small></div>{!readOnly&&<div><button disabled={busy} onClick={()=>void searchAction('run-search',s.id)}>Run now</button><button disabled={busy} onClick={()=>void searchAction('toggle-search',s.id,!s.enabled)}>{s.enabled?'Pause':'Resume'}</button><button disabled={busy} onClick={()=>void searchAction('remove-search',s.id)}>Remove</button></div>}</div>)}{!snapshot.searches.some(s=>s.kind===kind)&&<p className="miner-fine">Save a ZIP search above to start daily discovery.</p>}</article></>}
  {tab==='requests'&&<><article className="miner-card"><h2>Your own {kindLabel[kind].toLowerCase()} request form</h2><p>Share the link on your website, social profiles or with referral partners. Requests arrive in this workspace with the customer’s contact permission recorded.</p>{!readOnly&&<form onSubmit={e=>{e.preventDefault();void work(async()=>{const data=await api('campaigns',{action:'create',kind,name:name||`${kindLabel[kind]} request`,autoImport});setLink(new URL(data.path,window.location.origin).href);setName('');await refresh();setMessage('Form created. Share the link to start collecting requests.');})}}><div className="miner-controls"><label>Form title<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder={`${kindLabel[kind]} request`}/></label><button className="primary" disabled={busy}>Create request form</button></div><label className="miner-checkbox"><input type="checkbox" checked={autoImport} onChange={e=>setAutoImport(e.target.checked)}/>Automatically add new requests as leads. Matching contacts stay unchanged and their requests remain for review.</label></form>}{link&&<div className="miner-link"><label>Shareable form link<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button onClick={()=>void work(async()=>{await navigator.clipboard.writeText(link);setMessage('Link copied.');})}>Copy link</button><a href={link} target="_blank" rel="noreferrer">Preview form</a></div>}{campaigns.map(c=><div className="miner-saved-search" key={c.id}><div><b>{c.name}</b><small>{c.revoked?'Closed':Date.parse(c.expiresAt)<=(snapshot.checkedAt||0)?'Expired':c.autoImport===false?'Review requests before adding':'Adds new leads automatically'} · expires {new Date(c.expiresAt).toLocaleDateString()}</small></div>{!readOnly&&!c.revoked&&Date.parse(c.expiresAt)>(snapshot.checkedAt||0)&&<div><button disabled={busy} onClick={()=>void campaignAction('link',c.id)}>Get link</button><button disabled={busy} onClick={()=>void campaignAction('revoke',c.id)}>Close form</button></div>}</div>)}</article><article className="miner-card"><h2>Customer requests</h2>{!requests.length&&<p>No requests yet. Share a form to bring customers here.</p>}{requests.slice(0,100).map(i=><article className="miner-inquiry" key={i.id}><div><b>{i.name}</b><small>{i.phone} {i.email} · {i.zip} · {new Date(i.submittedAt).toLocaleString()}</small><p>{i.details||'Requested a response.'}</p><small>{i.status==='imported'?'Added as a new lead':'Awaiting review'} · {i.consentText}</small></div>{!readOnly&&i.status==='pending'&&<div><button disabled={busy} onClick={()=>void campaignAction('import',i.id)}>Add as new lead</button><button disabled={busy} onClick={()=>void campaignAction('dismiss',i.id)}>Dismiss</button></div>}</article>)}</article></>}
  {tab==='prospects'&&<article className="miner-card"><h2>{kindLabel[kind]} prospects</h2><label>Find a prospect<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Name, phone, email or address"/></label><div className="miner-table-scroll"><table className="miner-table"><thead><tr><th>Prospect</th><th>Contact</th><th>Origin</th></tr></thead><tbody>{prospects.slice(0,300).map(p=><tr key={p.id}><td>{onOpen?<button className="miner-contact-name" onClick={()=>onOpen(p.id)}>{p.name}</button>:<b>{p.name}</b>}<small>{p.address} {p.zip}</small></td><td>{p.phone||p.email||'Contact research needed'}{p.phone&&p.email&&<small>{p.email}</small>}</td><td>{p.extraFields?.['Data provider']||p.source}<small>{p.extraFields?.['Record type']||p.product}</small></td></tr>)}</tbody></table></div>{!prospects.length&&<p>Discover a source or share a request form to add your first prospects.</p>}{prospects.length>300&&<p>Showing 300 matches. Use search to narrow the list.</p>}</article>}
 </section>;
}
