'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {visibleNoteReminders,type NoteReminder} from '../lib/note-reminders';
import type {DocumentInsight} from '../lib/review-context';
export default function NoteReminders({leads,onOpen}:{leads:Array<{id:number;name:string}>;onOpen:(id:number)=>void}){
 const [items,setItems]=useState<NoteReminder[]>([]),[documents,setDocuments]=useState<DocumentInsight[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[reviewing,setReviewing]=useState(false),[view,setView]=useState('due'),[now,setNow]=useState(Date.now),[pending,setPending]=useState(0),[reviewed,setReviewed]=useState('');
 const running=useRef(false),mutating=useRef(false),generation=useRef(0),alive=useRef(true);
 const load=useCallback(async(action='',id?:string,hours?:number)=>{
  const mutation=Boolean(action&&!action.startsWith('review'));
  if(mutation?mutating.current:running.current)return;
  if(mutation){mutating.current=true;generation.current++;setBusy(id||action)}else{running.current=true;if(action)setReviewing(true)}
  const version=generation.current;
  try{const response=await fetch('/api/crm/note-reminders',action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,hours})}:{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Today could not load.');if(alive.current&&version===generation.current){setItems(old=>JSON.stringify(old)===JSON.stringify(data.items)?old:data.items||[]);setDocuments(data.documents||[]);setError(data.error||data.review?.error||(!data.configured?'Connect OpenAI in Settings to review activity.':''));setNow(Date.now());setPending(data.pending||0);setReviewed(data.review?.lastRunAt?new Date(data.review.lastRunAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'')}}
  catch(e){if(alive.current)setError(e instanceof Error?e.message:'Today could not load.')}finally{if(mutation){mutating.current=false;if(alive.current)setBusy('')}else{running.current=false;if(alive.current)setReviewing(false)}}
 },[]);
 useEffect(()=>{alive.current=true;const initial=window.setTimeout(()=>{void load().then(()=>{if(alive.current)void load('review')})},0);const timer=window.setInterval(()=>{if(document.visibilityState!=='hidden')void load('review')},20000);return()=>{alive.current=false;window.clearTimeout(initial);window.clearInterval(timer)}},[load]);
 useEffect(()=>{const refresh=()=>void load();window.addEventListener('pacifica:ai-review',refresh);return()=>window.removeEventListener('pacifica:ai-review',refresh)},[load]);
 const names=useMemo(()=>new Map(leads.map(l=>[l.id,l.name])),[leads]);
 const due=useMemo(()=>visibleNoteReminders(items,now),[items,now]);
 const shown=useMemo(()=>view==='done'?items.filter(t=>t.status==='done'):view==='dismissed'?items.filter(t=>t.status==='dismissed'):view==='later'?items.filter(t=>t.status==='open'&&!visibleNoteReminders([t],now).length):due,[items,view,now,due]);
 const groups=useMemo(()=>{const grouped=new Map<number,NoteReminder[]>();for(const item of shown.slice(0,60))grouped.set(item.leadId,[...(grouped.get(item.leadId)||[]),item]);return [...grouped.entries()]},[shown]);
 return <section className="note-reminders today-focus"><header><div><span className="today-eyebrow">YOUR DAY, IN FOCUS</span><h2>{due.length?`${due.length} ${due.length===1?'thing':'things'} to move forward.`:'A little room to breathe.'}</h2><p>{reviewing?'Checking requests and later replies…':pending?'Reviewing recent conversations…':reviewed?`Activity reviewed at ${reviewed}`:'Your next actions, drawn from your conversations.'}</p></div><button className="today-refresh" disabled={Boolean(busy)||reviewing} onClick={()=>void load('review-now')} aria-label="Review activity">{reviewing?'Reviewing…':'↻ Review'}</button></header>
  <div className="note-reminder-tabs" role="group" aria-label="Reminder filter">{[['due','Today'],['later','Later'],['done','Done'],['dismissed','Removed']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}{id==='due'&&due.length>0&&<span>{due.length}</span>}</button>)}</div>
  {error&&<p role="alert" className="today-notice">{error}</p>}
  {groups.map(([leadId,tasks])=><section className="today-contact-group" key={leadId}><button className="note-contact" onClick={()=>onOpen(leadId)}><span className="today-contact-initial">{(names.get(leadId)||'C').slice(0,1)}</span>{names.get(leadId)||'Contact'}<span aria-hidden="true">↗</span></button><div>{tasks.map(t=><article className={`today-task ${t.status}`} key={t.id}><div className="today-task-main"><b>{t.title}</b>{t.dueAt&&<small className="today-due">{new Date(t.dueAt).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small>}<details><summary>{t.status==='open'?'Why this task':t.resolvedBy==='ai'?'Why AI resolved this':'Details'}</summary><p>{t.evidence}</p><small>{t.sourceLabel||'Call notes'}</small>{t.resolution&&<p>{t.resolution}</p>}{t.resolutionEvidence&&<blockquote>{t.resolutionEvidence}</blockquote>}</details></div><div className="note-task-actions">{t.status!=='open'?<button disabled={Boolean(busy)} onClick={()=>void load('reopen',t.id)}>Restore</button>:<><button className="today-complete" disabled={Boolean(busy)} onClick={()=>void load('done',t.id)} aria-label={`Mark ${t.title} done`}>✓<span>Done</span></button><details className="today-task-menu"><summary aria-label={`More options for ${t.title}`}>•••</summary><div><button disabled={Boolean(busy)} onClick={()=>void load('snooze',t.id,1)}>In one hour</button><button disabled={Boolean(busy)} onClick={()=>void load('snooze',t.id,24)}>Tomorrow</button><button disabled={Boolean(busy)} onClick={()=>void load('dismiss',t.id)}>Not a task</button></div></details></>}</div></article>)}</div></section>)}
  {!shown.length&&<div className="today-empty"><span aria-hidden="true">✦</span><p>{view==='done'?'Finished tasks will appear here.':view==='dismissed'?'Removed suggestions stay here for reference.':view==='later'?'Nothing set aside for later.':pending?'Checking what still needs your attention.':'No outstanding actions found.'}</p></div>}
  {shown.length>60&&<p className="today-notice">{shown.length-60} more actions. Finish or remove a few to see the rest.</p>}
  {documents.length>0&&<details className="today-documents"><summary>Document context <span>{documents.length}</span></summary>{documents.slice().reverse().slice(0,20).map(d=><article key={d.id}><b>{names.get(d.leadId)||'Contact'} · {d.name}</b><pre>{d.text}</pre><small>AI transcription · check the original</small></article>)}</details>}
 </section>;
}
