"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {visibleNoteReminders,type NoteReminder} from "../lib/note-reminders";
export default function NoteReminders({leads,onOpen}:{leads:Array<{id:number;name:string}>;onOpen:(id:number)=>void}){
 const [items,setItems]=useState<NoteReminder[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(""),[view,setView]=useState("due"),[now,setNow]=useState(Date.now),[pending,setPending]=useState(0);
 const running=useRef(false),alive=useRef(true);
 const load=useCallback(async(action="",id?:string,hours?:number)=>{
  if(running.current)return;running.current=true;if(action)setBusy(id||action);
  try{const response=await fetch("/api/crm/note-reminders",action?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id,hours})}:{cache:"no-store"});const data=await response.json();if(!response.ok)throw Error(data.error||"Reminders could not load.");if(alive.current){setItems(old=>JSON.stringify(old)===JSON.stringify(data.items)?old:data.items||[]);setError(data.error||data.review?.error||(!data.configured?"Connect OpenAI in Settings to review your notes.":""));setNow(Date.now());setPending(data.pending||0)}}
  catch(e){if(alive.current)setError(e instanceof Error?e.message:"Reminders could not load.")}finally{running.current=false;if(alive.current)setBusy("")}
 },[]);
 useEffect(()=>{alive.current=true;const initial=window.setTimeout(()=>{void load().then(()=>{if(alive.current)void load("review")})},0);const timer=window.setInterval(()=>{if(document.visibilityState!=="hidden")void load("review")},60000);return()=>{alive.current=false;window.clearTimeout(initial);window.clearInterval(timer)}},[load]);
 const names=useMemo(()=>new Map(leads.map(l=>[l.id,l.name])),[leads]);
 const shown=useMemo(()=>view==="done"?items.filter(t=>t.status==="done"):view==="later"?items.filter(t=>t.status==="open"&&!visibleNoteReminders([t],now).length):visibleNoteReminders(items,now),[items,view,now]);
 return <section className="note-reminders"><header><div><h2>From your notes</h2><span>{visibleNoteReminders(items,now).length} to do</span></div><button disabled={Boolean(busy)} onClick={()=>void load("review-now")}>{busy.startsWith("review")?"Reviewing…":"Review notes"}</button></header><div className="note-reminder-tabs" role="group" aria-label="Reminder filter">{[["due","Today"],["later","Later"],["done","Done"]].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div>{error&&<p role="alert">{error}</p>}{pending>0&&<p role="status">{pending} contacts awaiting note review. Reviews continue in batches.</p>}{shown.slice(0,80).map(t=><article key={t.id}><div><button className="note-contact" onClick={()=>onOpen(t.leadId)}>{names.get(t.leadId)||"Contact"}</button><b>{t.title}</b><details><summary>View note</summary><p>{t.evidence}</p></details>{t.dueAt&&<small>{new Date(t.dueAt).toLocaleString()}</small>}</div><div className="note-task-actions">{t.status==="done"?<button disabled={Boolean(busy)} onClick={()=>void load("reopen",t.id)}>Undo</button>:<><button className="primary" disabled={Boolean(busy)} onClick={()=>void load("done",t.id)}>✓ Done</button><button disabled={Boolean(busy)} onClick={()=>void load("snooze",t.id,1)}>In 1 hour</button><button disabled={Boolean(busy)} onClick={()=>void load("snooze",t.id,24)}>Tomorrow</button></>}</div></article>)}{!shown.length&&<p>{view==="done"?"Completed reminders appear here.":view==="later"?"No reminders waiting for later.":pending?"Reviewing notes for outstanding actions…":"You're caught up. New actions from your notes appear here."}</p>}{shown.length>80&&<p>{shown.length-80} more reminders will appear as you finish these.</p>}</section>;
}
