'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {type OfficeItem} from '../lib/office-schedule';
import type {WorkspaceProfile} from '../lib/workspace-profile';
import AutomationStudio from './AutomationStudio';
type Contact={id:number;name:string;phone:string;deletedAt?:string};
const dateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export default function OfficeDesk({leads,profile,onProfile,isOwner,onOpen}:{leads:Contact[];profile:WorkspaceProfile;onProfile:(profile:WorkspaceProfile)=>void;isOwner:boolean;onOpen:(id:number)=>void}){
 const [items,setItems]=useState<OfficeItem[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selectedDay,setSelectedDay]=useState('');
 const [form,setForm]=useState({leadId:'',kind:'appointment',title:'',dueAt:'',amount:'',reminder:false,reminderAt:''});
 const revision=useRef(0),mutating=useRef(false);
 const load=useCallback(async()=>{if(mutating.current)return;const version=++revision.current;const response=await fetch('/api/crm/office',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error);if(version===revision.current)setItems(data.items||[])},[]);
 useEffect(()=>{const requests=revision;const initial=window.setTimeout(()=>void load().catch(e=>setMessage(e.message)),0);const timer=window.setInterval(()=>void load().catch(()=>undefined),30000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);requests.current++}},[load]);
 const days=useMemo(()=>Array.from({length:42},(_,index)=>new Date(month.getFullYear(),month.getMonth(),index-month.getDay()+1)),[month]);
 const visible=items.filter(item=>!selectedDay||dateKey(new Date(item.dueAt))===selectedDay).sort((a,b)=>Date.parse(a.dueAt)-Date.parse(b.dueAt));
 async function save(body:Record<string,unknown>){if(mutating.current)return;mutating.current=true;revision.current++;setBusy(true);setMessage('');try{const response=await fetch('/api/crm/office',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error);setItems(data.items);setMessage('Saved.');if(body.action==='create')setForm(f=>({...f,title:'',amount:'',reminder:false,reminderAt:''}))}catch(e){setMessage(e instanceof Error?e.message:'Could not save.')}finally{mutating.current=false;setBusy(false)}}
 return <section className="office-desk"><header><span className="eyebrow">OFFICE</span><h1>Calendar & payments</h1><p>Appointments, payment due dates, and scheduled reminders for this workspace. Times are shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}.</p></header>{isOwner&&<AutomationStudio profile={profile} onChange={onProfile}/>}
 <div className="office-calendar"><header><button aria-label="Previous month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>←</button><h2>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button aria-label="Next month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>→</button></header><div className="office-week">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><b key={day}>{day}</b>)}</div><div className="office-month">{days.map(day=>{const key=dateKey(day),count=items.filter(x=>x.status==='open'&&dateKey(new Date(x.dueAt))===key).length;return <button key={key} aria-label={`${day.toDateString()}, ${count} open items`} aria-pressed={selectedDay===key} className={day.getMonth()!==month.getMonth()?'outside':''} onClick={()=>{setSelectedDay(key);setForm(f=>({...f,dueAt:key+'T09:00'}))}}><b>{day.getDate()}</b>{count>0&&<small>{count} scheduled</small>}</button>})}</div></div>
 <section><h2>Add an appointment or payment</h2><form className="office-form" onSubmit={e=>{e.preventDefault();void save({action:'create',...form,leadId:Number(form.leadId),amount:Number(form.amount)||0,dueAt:new Date(form.dueAt).toISOString(),reminderAt:form.reminder?new Date(form.reminderAt).toISOString():'',reminderState:form.reminder?'pending':'off'})}}><label>Contact<select required value={form.leadId} onChange={e=>setForm(f=>({...f,leadId:e.target.value}))}><option value="">Choose contact</option>{leads.filter(x=>!x.deletedAt).map(lead=><option key={lead.id} value={lead.id}>{lead.name} · {lead.phone}</option>)}</select></label><label>Type<select value={form.kind} onChange={e=>setForm(f=>({...f,kind:e.target.value}))}><option value="appointment">Appointment</option><option value="payment">Payment due</option></select></label><label>Internal title<input required maxLength={100} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Consultation / Monthly payment"/></label><label>Date and time<input required type="datetime-local" value={form.dueAt} onChange={e=>setForm(f=>({...f,dueAt:e.target.value}))}/></label>{form.kind==='payment'&&<label>Amount due ($)<input type="number" min="0" max="10000000" step="0.01" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))}/></label>}<label><input type="checkbox" checked={form.reminder} onChange={e=>setForm(f=>({...f,reminder:e.target.checked}))}/> Schedule a text reminder</label>{form.reminder&&<label>Remind at<input required type="datetime-local" max={form.dueAt||undefined} value={form.reminderAt} onChange={e=>setForm(f=>({...f,reminderAt:e.target.value}))}/></label>}<button disabled={busy}>Save to calendar</button></form><p>Reminders send automatically when automation is active and texting is connected, subject to the contact’s text permission. The message includes the office name, date/time and payment amount when relevant; the internal title stays private. Server checks run daily at 16:00 UTC and every five minutes while the CRM is open. A reminder time is the earliest eligible check, not a guaranteed delivery time.</p>{!profile.serverAutomationEnabled&&<p>Automation is paused. Scheduled reminders will wait until it is enabled.</p>}</section>
 <section><header className="office-list-header"><h2>{selectedDay?`Scheduled for ${selectedDay}`:'All scheduled items'}</h2><button onClick={()=>setSelectedDay('')}>Show all</button></header>{visible.map(item=><article className="office-item" key={item.id}><div><b>{item.title}</b><p>{leads.find(l=>l.id===item.leadId)?.name||'Unavailable contact'} · {new Date(item.dueAt).toLocaleString()}{item.kind==='payment'?` · $${item.amount.toFixed(2)}`:''}</p><small>{item.status==='done'?(item.kind==='payment'?'Marked paid':'Completed'):`Reminder: ${item.reminderState}${item.reminderAt?' · '+new Date(item.reminderAt).toLocaleString():''}`}</small>{item.reminderError&&<p role="status">{item.reminderError}</p>}{item.reminderState==='sending'&&<p>Submission in progress or awaiting confirmation. Check Messages before following up.</p>}</div><div><button onClick={()=>onOpen(item.leadId)}>Contact</button>{item.status==='open'&&<button disabled={busy} onClick={()=>void save({action:'complete',id:item.id})}>{item.kind==='payment'?'Mark paid':'Complete'}</button>}{item.reminderState==='pending'&&<button disabled={busy} onClick={()=>void save({action:'cancel-reminder',id:item.id})}>Cancel reminder</button>}<button disabled={busy||item.reminderState==='sending'} onClick={()=>void save({action:'delete',id:item.id})}>Remove</button></div></article>)}{!visible.length&&<p>No items scheduled.</p>}</section><p role="status">{message}</p></section>
}
