'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {type OfficeItem} from '../lib/office-schedule';
import type {WorkspaceProfile} from '../lib/workspace-profile';
import {useDialogFocus} from '../hooks/use-dialog-focus';
import AutomationStudio from './AutomationStudio';
import CalendarConnection from './CalendarConnection';
import {calendarAlertKey} from './CalendarAlerts';
import styles from './OfficeDesk.module.css';

type Contact={id:number;name:string;phone:string;deletedAt?:string;followUp?:string};
type Entry=Omit<OfficeItem,'kind'>&{kind:OfficeItem['kind']|'follow-up'};
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const localTime=(value:string)=>{const d=new Date(value);return `${dateKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
const clock=(value:string)=>new Date(value).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});
const label=(kind:Entry['kind'])=>kind==='payment'?'Payment':kind==='follow-up'?'Follow-up':'Appointment';
const blank=(date=new Date())=>({id:'',leadId:'0',kind:'appointment',title:'',dueAt:dateKey(date)+'T09:00',amount:'',durationMinutes:30,staffReminderMinutes:15,reminder:false,reminderAt:''});

export default function OfficeDesk({leads,profile,onProfile,isOwner,onOpen,workspaceId='local'}:{workspaceId?:string;leads:Contact[];profile:WorkspaceProfile;onProfile:(profile:WorkspaceProfile)=>void;isOwner:boolean;onOpen:(id:number)=>void}){
 const [items,setItems]=useState<OfficeItem[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [anchor,setAnchor]=useState(()=>new Date()),[view,setView]=useState<'month'|'week'|'agenda'>('month'),[selected,setSelected]=useState('');
 const [editor,setEditor]=useState(false),[settings,setSettings]=useState(false),[deviceAlerts,setDeviceAlerts]=useState(false),[form,setForm]=useState(blank);
 const [filters,setFilters]=useState({appointment:true,payment:true,'follow-up':true,completed:false});
 const revision=useRef(0),mutating=useRef(false),dialog=useRef<HTMLDivElement>(null);
 useDialogFocus(dialog,editor||settings,()=>{if(!busy){setEditor(false);setSettings(false)}});
 const load=useCallback(async()=>{if(mutating.current)return;const version=++revision.current;const response=await fetch('/api/crm/office',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Calendar could not load.');if(version===revision.current)setItems(data.items||[])},[]);
 useEffect(()=>{const requests=revision;const initial=setTimeout(()=>{void load().catch(e=>setMessage(e.message));try{setDeviceAlerts(localStorage.getItem(calendarAlertKey(workspaceId))==='on')}catch{}},0),timer=setInterval(()=>void load().catch(()=>undefined),30000);return()=>{clearTimeout(initial);clearInterval(timer);requests.current++}},[load,workspaceId]);
 const contacts=useMemo(()=>new Map(leads.filter(x=>!x.deletedAt).map(x=>[x.id,x])),[leads]);
 const entries=useMemo(()=>{
  const followUps:Entry[]=leads.filter(x=>!x.deletedAt&&x.followUp&&Number.isFinite(Date.parse(x.followUp))).map(x=>({id:`followup:${x.id}`,leadId:x.id,kind:'follow-up',title:x.name,dueAt:x.followUp!,amount:0,status:'open',reminderAt:'',reminderState:'off',createdAt:''}));
  return [...items.filter(x=>x.leadId===0||contacts.has(x.leadId)),...followUps].sort((a,b)=>Date.parse(a.dueAt)-Date.parse(b.dueAt));
 },[items,leads,contacts]);
 const filtered=entries.filter(x=>filters[x.kind]&&(filters.completed||x.status==='open'));
 const monthDays=useMemo(()=>Array.from({length:42},(_,i)=>new Date(anchor.getFullYear(),anchor.getMonth(),i-new Date(anchor.getFullYear(),anchor.getMonth(),1).getDay()+1)),[anchor]);
 const days=view==='week'?Array.from({length:7},(_,i)=>new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()-anchor.getDay()+i)):monthDays;
 const byDay=new Map<string,Entry[]>();for(const entry of filtered){const key=dateKey(new Date(entry.dueAt));byDay.set(key,[...(byDay.get(key)||[]),entry])}
 const active=entries.find(x=>x.id===selected),today=dateKey(new Date());
 function move(direction:number){setAnchor(date=>view==='week'?new Date(date.getFullYear(),date.getMonth(),date.getDate()+direction*7):new Date(date.getFullYear(),date.getMonth()+direction,1))}
 function create(date=anchor){setForm(blank(date));setSelected('');setSettings(false);setEditor(true);setMessage('')}
 function edit(item:Entry){if(item.kind==='follow-up'){onOpen(item.leadId);return}setForm({id:item.id,leadId:String(item.leadId),kind:item.kind,title:item.title,dueAt:localTime(item.dueAt),amount:String(item.amount),durationMinutes:item.durationMinutes??30,staffReminderMinutes:item.staffReminderMinutes??15,reminder:item.reminderState==='pending',reminderAt:item.reminderAt?localTime(item.reminderAt):''});setEditor(true);setMessage('')}
 async function save(body:Record<string,unknown>){
  if(mutating.current)return;mutating.current=true;revision.current++;setBusy(true);setMessage('');
  try{const response=await fetch('/api/crm/office',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not save.');setItems(data.items);setEditor(false);setMessage('Saved.');window.dispatchEvent(new Event('pacifica:calendar-changed'))}
  catch(e){setMessage(e instanceof Error?e.message:'Could not save.')}finally{mutating.current=false;setBusy(false)}
 }
 async function toggleAlerts(){const enabled=!deviceAlerts;try{if(enabled&&typeof Notification!=='undefined'&&Notification.permission==='default')await Notification.requestPermission();localStorage.setItem(calendarAlertKey(workspaceId),enabled?'on':'off');setDeviceAlerts(enabled);setMessage(enabled?(typeof Notification!=='undefined'&&Notification.permission==='granted'?'Desktop and in-app reminders enabled. Keep Pacifica running.':'In-app reminders enabled. Allow browser notifications for desktop pop-ups.'):'Device reminders disabled.');window.dispatchEvent(new Event('pacifica:calendar-changed'))}catch{setMessage('Check your browser notification permissions.')}}
 function chip(item:Entry){return <button key={item.id} type="button" className={`${styles.event} ${styles[item.kind]} ${item.status==='done'?styles.done:''}`} onClick={()=>{setSelected(item.id);setMessage('')}} title={`${item.title} · ${clock(item.dueAt)}`}><span>{clock(item.dueAt)}</span> {item.title}</button>}
 return <section className={styles.calendar}>
  <header className={styles.toolbar}><h1>Calendar</h1><button onClick={()=>setAnchor(new Date())}>Today</button><div className={styles.arrows}><button aria-label="Previous period" onClick={()=>move(-1)}>‹</button><button aria-label="Next period" onClick={()=>move(1)}>›</button></div><h2>{anchor.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><div className={styles.toolbarEnd}><select aria-label="Calendar view" value={view} onChange={e=>setView(e.target.value as typeof view)}><option value="month">Month</option><option value="week">Week</option><option value="agenda">Agenda</option></select><button onClick={()=>{setSettings(true);setEditor(false)}}>Calendar settings</button><button className={styles.primary} onClick={()=>create()}>+ Create</button></div></header>
  <div className={styles.workspace}>
   <aside className={styles.sidebar}><div className={styles.miniMonth} aria-label="Choose a date">{['S','M','T','W','T','F','S'].map((d,i)=><b key={i}>{d}</b>)}{monthDays.map(day=><button key={dateKey(day)} className={dateKey(day)===today?styles.today:day.getMonth()!==anchor.getMonth()?styles.outside:''} aria-label={`Go to ${day.toDateString()}`} onClick={()=>{setAnchor(day);setView('week')}}>{day.getDate()}</button>)}</div><h3>My calendar</h3>{(['appointment','payment','follow-up'] as const).map(kind=><label className={styles.filter} key={kind}><input type="checkbox" checked={filters[kind]} onChange={e=>setFilters(f=>({...f,[kind]:e.target.checked}))}/><i className={styles[kind]}/>{label(kind)}s</label>)}<label className={styles.filter}><input type="checkbox" checked={filters.completed} onChange={e=>setFilters(f=>({...f,completed:e.target.checked}))}/>Show completed</label><p className={styles.timezone}>{Intl.DateTimeFormat().resolvedOptions().timeZone}</p><p className={styles.hint}>Click a date to create an event. Click an event for details.</p></aside>
   <main className={styles.board}>
    {view==='agenda'?<div className={styles.agenda}>{filtered.filter(x=>new Date(x.dueAt).getMonth()===anchor.getMonth()&&new Date(x.dueAt).getFullYear()===anchor.getFullYear()).map(item=><article key={item.id}><time>{new Date(item.dueAt).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</time>{chip(item)}</article>)}{!filtered.some(x=>new Date(x.dueAt).getMonth()===anchor.getMonth()&&new Date(x.dueAt).getFullYear()===anchor.getFullYear())&&<p>No events this month. Create an appointment to get started.</p>}</div>:<><div className={styles.weekdays}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><b key={day}>{day}</b>)}</div><div className={`${styles.grid} ${view==='week'?styles.week:''}`}>{days.map(day=>{const key=dateKey(day),events=byDay.get(key)||[];return <div className={`${styles.day} ${day.getMonth()!==anchor.getMonth()?styles.outside:''}`} key={key}><button className={`${styles.date} ${key===today?styles.today:''}`} aria-label={`Create event on ${day.toDateString()}`} onClick={()=>create(day)}>{day.getDate()}</button><div className={styles.dayEvents}>{events.slice(0,view==='week'?events.length:4).map(chip)}{view==='month'&&events.length>4&&<button className={styles.more} onClick={()=>{setAnchor(day);setView('week')}}>+{events.length-4} more</button>}</div><button className={styles.addSpace} aria-label={`Add event on ${day.toDateString()}`} onClick={()=>create(day)}/></div>})}</div></>}
   </main>
  </div>
  {active&&!editor&&!settings&&<section className={styles.detail} aria-label="Event details"><header><span>{label(active.kind)}</span><button aria-label="Close event details" onClick={()=>setSelected('')}>×</button></header><h2>{active.title}</h2><p>{new Date(active.dueAt).toLocaleString()}{active.kind==='payment'?` · $${active.amount.toFixed(2)}`:''}</p>{active.leadId>0&&<p>{contacts.get(active.leadId)?.name}</p>}<p>{active.status==='done'?(active.kind==='payment'?'Marked paid':'Completed'):active.kind==='follow-up'?'Saved on the contact record':`Your reminder: ${active.staffReminderMinutes===-1?'off':(active.staffReminderMinutes??15)+' minutes before'}`}</p>{active.reminderState!=='off'&&<p>Customer text: {active.reminderState}</p>}{active.reminderError&&<p role="status">{active.reminderError}</p>}<div className={styles.actions}>{active.leadId>0&&<button onClick={()=>onOpen(active.leadId)}>Contact</button>}{active.status==='open'&&<button disabled={busy||active.reminderState==='sending'} onClick={()=>edit(active)}>Edit</button>}{active.kind!=='follow-up'&&<>{active.status==='open'&&<button disabled={busy} onClick={()=>void save({action:'complete',id:active.id})}>{active.kind==='payment'?'Mark paid':'Complete'}</button>}{active.reminderState==='pending'&&<button disabled={busy} onClick={()=>void save({action:'cancel-reminder',id:active.id})}>Cancel customer text</button>}<button disabled={busy||active.reminderState==='sending'} onClick={()=>{if(window.confirm('Remove this event and its synced Google event?'))void save({action:'delete',id:active.id})}}>Remove</button></>}</div></section>}
  {(editor||settings)&&<div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!busy){setEditor(false);setSettings(false)}}}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="calendar-dialog-title" className={styles.dialog}><header><h2 id="calendar-dialog-title">{settings?'Calendar settings':form.id?'Edit event':'New event'}</h2><button disabled={busy} aria-label="Close calendar dialog" onClick={()=>{setEditor(false);setSettings(false)}}>×</button></header>
   {settings?<><CalendarConnection/><section><h3>Your device reminders</h3><p>In-app and desktop alerts while Pacifica is running. Phone reminders are in More → Calendar in the Pacifica app.</p><button aria-pressed={deviceAlerts} onClick={()=>void toggleAlerts()}>{deviceAlerts?'Turn off device reminders':'Enable device reminders'}</button><small>Use Google or Pacifica reminders to avoid receiving both.</small></section>{isOwner&&<details><summary>Customer text automation</summary><AutomationStudio profile={profile} onChange={onProfile}/></details>}</>:<form id="calendar-editor" className={styles.form} onSubmit={e=>{e.preventDefault();void save({action:form.id?'edit':'create',...form,leadId:Number(form.leadId),amount:Number(form.amount)||0,dueAt:new Date(form.dueAt).toISOString(),reminderAt:form.reminder?new Date(form.reminderAt).toISOString():'',reminderState:form.reminder?'pending':'off'})}}>
    <label className={styles.wide}>Title<input required autoFocus maxLength={100} placeholder="Add a title" value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))}/></label>
    <label>Type<select value={form.kind} onChange={e=>setForm(f=>({...f,kind:e.target.value}))}><option value="appointment">Appointment</option><option value="payment">Payment due</option></select></label><label>Contact<select value={form.leadId} onChange={e=>setForm(f=>({...f,leadId:e.target.value,reminder:e.target.value==='0'?false:f.reminder}))}><option value="0">Personal / no contact</option>{[...contacts.values()].map(lead=><option key={lead.id} value={lead.id}>{lead.name}</option>)}</select></label>
    <label>Date and time<input required type="datetime-local" value={form.dueAt} onChange={e=>setForm(f=>({...f,dueAt:e.target.value}))}/></label><label>Duration<select value={form.durationMinutes} onChange={e=>setForm(f=>({...f,durationMinutes:Number(e.target.value)}))}>{[15,30,45,60,90,120].map(minutes=><option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label>
    <label>Remind me<select value={form.staffReminderMinutes} onChange={e=>setForm(f=>({...f,staffReminderMinutes:Number(e.target.value)}))}>{[[-1,'No reminder'],[0,'At the start'],[5,'5 minutes before'],[15,'15 minutes before'],[30,'30 minutes before'],[60,'1 hour before'],[1440,'1 day before']].map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>{form.kind==='payment'&&<label>Amount due ($)<input type="number" min="0" max="10000000" step="0.01" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))}/></label>}
    <details className={styles.wide}><summary>Customer text reminder</summary><label className={styles.check}><input type="checkbox" disabled={form.leadId==='0'} checked={form.reminder} onChange={e=>setForm(f=>({...f,reminder:e.target.checked}))}/>Schedule a customer text</label>{form.reminder&&<label>Remind at<input required type="datetime-local" max={form.dueAt} value={form.reminderAt} onChange={e=>setForm(f=>({...f,reminderAt:e.target.value}))}/></label>}<small>Requires a saved contact, text permission, connected texting, and active automation. Checks run daily at 16:00 UTC and every five minutes while the CRM is open. The selected time is the earliest check.</small></details>
    <footer className={styles.wide}><button type="button" disabled={busy} onClick={()=>setEditor(false)}>Cancel</button><button className={styles.primary} disabled={busy}>{busy?'Saving…':form.id?'Save changes':'Save to calendar'}</button></footer>
   </form>}<p role="status">{message}</p>
  </div></div>}
  {!editor&&!settings&&message&&<p role="status" className={styles.status}>{message}</p>}
 </section>;
}
