'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import type {OpportunityLead} from '../lib/opportunities';
import type {QuoteSubmission} from '../lib/quote-intake';
import {displayBirthDate} from '../lib/lead-presentation';
import {contactMatches} from '../lib/contact-sync';
import styles from './OpportunityDesk.module.css';
export default function OpportunityDesk({leads,initialLeadId,onOpen,onRefresh}:{leads:OpportunityLead[];initialLeadId?:number|null;onOpen:(id:number)=>void;onMessage:(id:number)=>void;onRefresh:()=>Promise<void>}){
 const [freshLink,setFreshLink]=useState(''),[submissions,setSubmissions]=useState<QuoteSubmission[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[source,setSource]=useState('Website quote request'),[leadId,setLeadId]=useState(initialLeadId?String(initialLeadId):'');
 const load=useCallback(async()=>{const response=await fetch('/api/crm/opportunities',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to load quote requests.');setSubmissions(data.submissions||[])},[]);
 useEffect(()=>{let canceled=false;const refresh=()=>{if(document.hidden)return;void load().catch(e=>{if(!canceled)setError(e.message)})};refresh();const timer=window.setInterval(refresh,30000);return()=>{canceled=true;window.clearInterval(timer)}},[load]);
 const matches=useMemo(()=>{const selected=leads.find(l=>String(l.id)===leadId&&!l.deletedAt&&!l.doNotCall);const found=leads.filter(l=>!l.deletedAt&&!l.doNotCall&&contactMatches({name:l.name,phone:l.phone,email:l.email||''},search)).slice(0,50);return selected&&!found.some(l=>l.id===selected.id)?[selected,...found]:found},[leads,search,leadId]);
 const pending=submissions.filter(s=>s.status==='pending');
 async function action(body:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/crm/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to save.');if(body.action==='create-link'){setFreshLink(data.path);setNotice('Ready to copy. This link expires in 7 days.');return}await load();if(body.action==='accept'){await onRefresh();setNotice('Reviewed details saved. Existing filled fields and contact restrictions are preserved.')}else setNotice('Saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 async function copy(path:string){try{await navigator.clipboard.writeText(new URL(path,window.location.origin).href);setFreshLink('');setNotice('Link copied. Ready to share.')}catch{setError('Copy the link from the field below.')}}
 return <section className={styles.desk}><header><h2>Quote requests</h2></header>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <section className={styles.panel}><h2>Collect quote details</h2><p>Search your saved contacts by name or phone. Personal links collect missing DOB and optional renewal/VIN details. A general link lets new prospects request a quote.</p><div className={styles.controls}><label>Find a saved contact<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or phone number"/></label><label>Link for<select value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">New prospects / referrals</option>{matches.map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label>{!leadId&&<label>Source label<input value={source} onChange={e=>setSource(e.target.value)} placeholder="Website / Realtor referral / Email signature" maxLength={80}/></label>}<button disabled={busy} onClick={()=>void action({action:'create-link',leadId:leadId?Number(leadId):null,source})}>Create quote link</button></div>
 <p>Use a general link on your website, in your email signature, or with referral partners. The prospect submits their own details; creating a link does not create a lead or send a message.</p>
 {freshLink&&<div className={styles.link}><input aria-label="New quote link" readOnly value={typeof window!=='undefined'?new URL(freshLink,window.location.origin).href:freshLink}/><button onClick={()=>void copy(freshLink)}>Copy link</button><button onClick={()=>{setFreshLink('');setNotice('')}}>Done</button></div>}</section>
 <section className={styles.panel}><h2>Quote requests to review</h2><p>These details are prospect-reported. Confirm the person and review their information before saving. Only empty contact fields are filled.</p>{pending.length?pending.map(s=><article className={styles.request} key={s.id}><header><h3>{s.details.name||leads.find(l=>l.id===s.leadId)?.name||'Contact quote details'}</h3><span>{s.source} · {new Date(s.submittedAt).toLocaleString()}</span></header><dl><div><dt>Phone</dt><dd>{s.details.phone||leads.find(l=>l.id===s.leadId)?.phone||'On contact record'}</dd></div><div><dt>Date of birth</dt><dd>{displayBirthDate(s.details.dateOfBirth)}</dd></div><div><dt>Address</dt><dd>{[s.details.address,s.details.city,s.details.state,s.details.zip].filter(Boolean).join(', ')||'On contact record'}</dd></div><div><dt>Product</dt><dd>{s.details.product||'On contact record'}</dd></div><div><dt>Renewal</dt><dd>{s.details.renewalDate||'Not supplied'}</dd></div><div><dt>VIN</dt><dd>{s.details.vin||'Not supplied'}</dd></div><div><dt>Current carrier</dt><dd>{s.details.currentCarrier||'Not supplied'}</dd></div></dl><details><summary>Quote request permission</summary><p>{s.consentText}</p></details><footer>{s.leadId&&<button onClick={()=>onOpen(s.leadId!)}>Open contact</button>}<button disabled={busy} onClick={()=>void action({action:'accept',id:s.id})}>Reviewed · save to CRM</button><button disabled={busy} onClick={()=>void action({action:'dismiss',id:s.id})}>Dismiss</button></footer></article>):<p>No pending requests yet. Share a quote link to start collecting them.</p>}</section>
 </section>
}
