'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {rankOpportunities,revenuePlan,type OpportunityLead} from '../lib/opportunities';
import type {QuoteLink,QuoteSubmission} from '../lib/quote-intake';
import {displayBirthDate} from '../lib/lead-presentation';
import {contactMatches} from '../lib/contact-sync';
import styles from './OpportunityDesk.module.css';
type Link=QuoteLink&{path:string};
export default function OpportunityDesk({leads,initialLeadId,onOpen,onMessage,onRefresh}:{leads:OpportunityLead[];initialLeadId?:number|null;onOpen:(id:number)=>void;onMessage:(id:number)=>void;onRefresh:()=>Promise<void>}){
 const collectRef=useRef<HTMLElement>(null);
 const [growthPlan,setGrowthPlan]=useState<{plan:string;mode:string;notice?:string}|null>(null);
 const [links,setLinks]=useState<Link[]>([]),[submissions,setSubmissions]=useState<QuoteSubmission[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[source,setSource]=useState('Website quote request'),[leadId,setLeadId]=useState(initialLeadId?String(initialLeadId):''),[filter,setFilter]=useState('All opportunities'),[plan,setPlan]=useState({goal:1000000,commission:500,closeRate:20});
 const load=useCallback(async()=>{const response=await fetch('/api/crm/opportunities',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to load quote requests.');setLinks(data.links||[]);setSubmissions(data.submissions||[])},[]);
 useEffect(()=>{let canceled=false;const refresh=()=>{if(document.hidden)return;void load().catch(e=>{if(!canceled)setError(e.message)})};refresh();const timer=window.setInterval(refresh,30000);return()=>{canceled=true;window.clearInterval(timer)}},[load]);
 const opportunities=useMemo(()=>rankOpportunities(leads),[leads]);
 const matches=useMemo(()=>{const selected=leads.find(l=>String(l.id)===leadId&&!l.deletedAt&&!l.doNotCall);const found=leads.filter(l=>!l.deletedAt&&!l.doNotCall&&contactMatches({name:l.name,phone:l.phone,email:l.email||''},search)).slice(0,50);return selected&&!found.some(l=>l.id===selected.id)?[selected,...found]:found},[leads,search,leadId]);
 const visible=opportunities.filter(({lead,signal})=>contactMatches({name:lead.name,phone:lead.phone,email:lead.email||''},search)&&(filter==='All opportunities'||filter==='Warm requests'&&signal.warm||filter==='Renewals'&&signal.kind==='renewal'));
 const pending=submissions.filter(s=>s.status==='pending'),goal=revenuePlan(plan.goal,plan.commission,plan.closeRate);
 async function action(body:Record<string,unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/crm/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to save.');if(body.action==='plan'){setGrowthPlan(data);return}await load();if(body.action==='accept'){await onRefresh();setNotice('Reviewed details saved. Existing filled fields and contact restrictions are preserved.')}else if(body.action==='create-link')setNotice('Quote link created. Copy it below to share.');else setNotice('Saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 async function copy(path:string){try{await navigator.clipboard.writeText(new URL(path,window.location.origin).href);setNotice('Link copied.')}catch{setError('Copy the link from the field below.')}}
 return <section className={styles.desk}><header><span className={styles.eyebrow}>GROW YOUR BOOK</span><h1>Opportunities</h1><p>Work real requests first. Collect missing details and prepare for recorded renewals.</p></header>
 <div className={styles.metrics}><article><b>{pending.length}</b><span>Requests to review</span></article><article><b>{opportunities.filter(x=>x.signal.warm).length}</b><span>Warm conversations</span></article><article><b>{opportunities.filter(x=>x.signal.kind==='renewal').length}</b><span>Renewals within 45 days</span></article></div>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <section ref={collectRef} className={styles.panel}><h2>Collect quote details</h2><p>Search your saved contacts by name or phone. Personal links collect missing DOB and optional renewal/VIN details. A general link lets new prospects request a quote.</p><div className={styles.controls}><label>Find a saved contact<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or phone number"/></label><label>Link for<select value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">New prospects / referrals</option>{matches.map(l=><option key={l.id} value={l.id}>{l.name} · {l.phone}</option>)}</select></label>{!leadId&&<label>Source label<input value={source} onChange={e=>setSource(e.target.value)} placeholder="Website / Realtor referral / Email signature" maxLength={80}/></label>}<button disabled={busy} onClick={()=>void action({action:'create-link',leadId:leadId?Number(leadId):null,source})}>Create quote link</button></div>
 <p>Use a general link on your website, in your email signature, or with referral partners. The prospect submits their own details; creating a link does not create a lead or send a message.</p>
 <details open><summary>Manage quote links ({links.filter(l=>!l.revoked).length})</summary>{links.filter(l=>!l.revoked).map(link=><div className={styles.link} key={link.id}><span>{link.leadId?leads.find(l=>l.id===link.leadId)?.name||'Contact details':link.source} · Expires {new Date(link.expiresAt).toLocaleDateString()}</span>{link.path?<><input aria-label={`Quote link ${link.id}`} readOnly value={typeof window!=='undefined'?new URL(link.path,window.location.origin).href:link.path}/><button onClick={()=>void copy(link.path)}>Copy link</button></>:<span>Expired</span>}<button disabled={busy} onClick={()=>void action({action:'revoke-link',id:link.id})}>Revoke</button></div>)}</details></section>
 <section className={styles.panel}><h2>Quote requests to review</h2><p>These details are prospect-reported. Confirm the person and review their information before saving. Only empty contact fields are filled.</p>{pending.length?pending.map(s=><article className={styles.request} key={s.id}><header><h3>{s.details.name||leads.find(l=>l.id===s.leadId)?.name||'Contact quote details'}</h3><span>{s.source} · {new Date(s.submittedAt).toLocaleString()}</span></header><dl><div><dt>Phone</dt><dd>{s.details.phone||leads.find(l=>l.id===s.leadId)?.phone||'On contact record'}</dd></div><div><dt>Date of birth</dt><dd>{displayBirthDate(s.details.dateOfBirth)}</dd></div><div><dt>Address</dt><dd>{[s.details.address,s.details.city,s.details.state,s.details.zip].filter(Boolean).join(', ')||'On contact record'}</dd></div><div><dt>Product</dt><dd>{s.details.product||'On contact record'}</dd></div><div><dt>Renewal</dt><dd>{s.details.renewalDate||'Not supplied'}</dd></div><div><dt>VIN</dt><dd>{s.details.vin||'Not supplied'}</dd></div><div><dt>Current carrier</dt><dd>{s.details.currentCarrier||'Not supplied'}</dd></div></dl><details><summary>Quote request permission</summary><p>{s.consentText}</p></details><footer><button disabled={busy} onClick={()=>void action({action:'accept',id:s.id})}>Reviewed · save to CRM</button><button disabled={busy} onClick={()=>void action({action:'dismiss',id:s.id})}>Dismiss</button></footer></article>):<p>No pending requests yet. Share a quote link to start collecting them.</p>}</section>
 <section className={styles.panel}><header className={styles.row}><h2>Your next conversations</h2><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All opportunities','Warm requests','Renewals'].map(x=><option key={x}>{x}</option>)}</select></label></header><p>Warm means a recent quote request or recorded interest. A renewal date alone does not establish interest.</p>{visible.map(({lead,signal})=><article className={styles.opportunity} key={lead.id}><div><b>{lead.name}</b><p>{lead.product} · {lead.phone}</p><span>{signal.label}</span><p>{signal.detail}</p></div><div><button onClick={()=>onOpen(lead.id)}>Open contact</button><button onClick={()=>onMessage(lead.id)}>Personal follow-up</button><button onClick={()=>{setLeadId(String(lead.id));setSearch(lead.name);collectRef.current?.scrollIntoView({block:"start"})}}>Collect details</button></div></article>)}{!visible.length&&<p>No matching opportunities. Imported names and phone numbers are not automatically labeled warm.</p>}</section>
 <section className={styles.panel}><header className={styles.row}><h2>Your weekly growth plan</h2><button disabled={busy} onClick={()=>void action({action:"plan"})}>{busy?"Working…":"Build my action plan"}</button></header><p>Use your actual request and renewal counts to plan personal follow-ups, referral partnerships, and website capture. AI prepares a plan for review; it does not contact anyone.</p>{growthPlan&&<div role="status"><b>{growthPlan.mode==="ai"?"AI draft · review before using":"Rules-based plan"}</b>{growthPlan.notice&&<p>{growthPlan.notice}</p>}<p className={styles.plan}>{growthPlan.plan}</p></div>}</section>
 <section className={styles.panel}><h2>Where requests come from</h2><p>Track submitted requests by the source label on each link.</p><div className={styles.sources}>{[...new Set(submissions.map(s=>s.source))].map(label=><article key={label}><b>{label}</b><span>{submissions.filter(s=>s.source===label).length} submitted · {submissions.filter(s=>s.source===label&&s.status==='accepted').length} reviewed · {leads.filter(l=>l.quoteRequests?.[0]?.source===label&&isWon(l)).length} won</span></article>)}</div></section>
 <details className={styles.panel}><summary>Plan toward a revenue goal</summary><p>Planning assumptions, not a forecast. Use annual commission revenue—not policy premium or personal take-home income.</p><div className={styles.controls}>{([['goal','Annual commission goal ($)'],['commission','Average commission per policy ($)'],['closeRate','Quote-request close rate (%)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="1" max={key==='closeRate'?100:undefined} value={plan[key]} onChange={e=>setPlan(p=>({...p,[key]:Number(e.target.value)}))}/></label>)}</div>{goal?<p>{goal.policies.toLocaleString()} policies/year require about {goal.requests.toLocaleString()} qualified requests/year ({goal.monthlyRequests.toLocaleString()}/month) at these assumptions.</p>:<p>Enter positive amounts and a close rate from 1 to 100%.</p>}</details>
 </section>
}
function isWon(lead:OpportunityLead){return /sold|won/i.test(lead.outcome||'')||Number(lead.closedRevenue)>0}
