'use client';
import {useState} from 'react';
import {quoteReadiness,type QuoteLead} from '../lib/quote-readiness';
import {quoteSourceEntries,quoteAddressLine} from '../lib/lead-quote-data';
export default function QuoteDesk({leads,onOpen,onQuote,onQuoted}:{leads:QuoteLead[];onOpen:(id:number)=>void;onQuote:(id:number)=>void;onQuoted:(id:number)=>void}){
 const [filter,setFilter]=useState('Ready to review');const [product,setProduct]=useState('All');const [search,setSearch]=useState('');
 const entries=leads.map(lead=>({lead,info:quoteReadiness(lead)})).filter(({info})=>info.kind&&!info.excluded);
 const visible=entries.filter(({lead,info})=>(product==='All'||info.kind===product)&&(filter==='Quoted'?info.quoted:!info.quoted&&(filter==='Needs information'?!info.ready:info.ready))&&`${lead.name} ${lead.phone} ${lead.email} ${info.vin}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.lead.received||a.lead.importedFields?.Received||'').localeCompare(b.lead.received||b.lead.importedFields?.Received||'')||a.lead.id-b.lead.id);
 return <div className="quote-desk"><header><h1>Quote desk</h1><p>Work through your auto and home leads, one at a time.</p><p>Ready means the basic checklist is filled in. Verify drivers, property details and coverage requirements in your carrier portal before quoting. Carrier pricing is not connected yet.</p></header><div className="quote-desk-tools"><label>List<select value={filter} onChange={e=>setFilter(e.target.value)}>{['Ready to review','Needs information','Quoted'].map(f=><option key={f}>{f}</option>)}</select></label><label>Product<select value={product} onChange={e=>setProduct(e.target.value)}>{['All','Auto','Home'].map(f=><option key={f}>{f}</option>)}</select></label><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, phone, email or VIN"/></label></div><p role="status">{visible.length} leads · {entries.filter(e=>e.info.ready&&!e.info.quoted).length} ready to review</p><div className="quote-desk-list">{visible.map(({lead,info})=><article key={lead.id}><header><div><small>{info.kind} · {lead.source||'Contact'}</small><h2>{lead.name}</h2><p>{quoteAddressLine(lead)||info.address||'Address missing'}</p>{info.vin&&<p>VIN: {info.vin}</p>}</div><span>{info.quoted?'Quoted':info.ready?'Basic details present':`${info.missing.length} details missing`}</span></header><ul>{info.checks.map(c=><li key={c.label}>{c.present?'✓':'○'} {c.label}{!c.present?' — missing':''}</li>)}</ul><details><summary>All received lead information</summary><dl>{quoteSourceEntries(lead).filter(f=>f.value).map(f=><div key={f.label}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl></details><footer><button onClick={()=>onOpen(lead.id)}>Contact details</button><button onClick={()=>onQuote(lead.id)}>Open quote workspace</button>{!info.quoted&&<button onClick={()=>onQuoted(lead.id)}>Mark quoted</button>}</footer></article>)}</div>{!visible.length&&<p>No leads in this list. Check “Needs information” to see which details to collect.</p>}</div>
}
