import test from 'node:test';
import assert from 'node:assert/strict';
import {GET,POST} from '../../app/api/calendar/outlook/route.ts';
import {GET as callback} from '../../app/api/calendar/outlook/callback/route.ts';
import {GET as feedGet,POST as feedPost} from '../../app/api/calendar/feed/route.ts';
import {GET as externalGet} from '../../app/api/calendar/external/route.ts';
import {readCalendarSecret,writeCalendarSecret} from '../../app/lib/calendar-vault.ts';
import {normalizeExternalEvent} from '../../app/lib/external-calendar.ts';
import {calendarFeed} from '../../app/lib/calendar-feed.ts';
const request=(body,origin='https://crm.test')=>new Request('https://crm.test/api/calendar/outlook',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)});
function setup(){Object.assign(process.env,{GOOGLE_CALENDAR_CLIENT_ID:'g-client',GOOGLE_CALENDAR_CLIENT_SECRET:'g-secret',GOOGLE_CALENDAR_REDIRECT_URI:'https://crm.test/api/calendar/google/callback',OUTLOOK_CALENDAR_CLIENT_ID:'o-client',OUTLOOK_CALENDAR_CLIENT_SECRET:'o-secret',GOOGLE_CALENDAR_ENCRYPTION_KEY:'cd'.repeat(32),OUTLOOK_CALENDAR_REDIRECT_URI:'https://crm.test/api/calendar/outlook/callback'});globalThis.calendarAccess={allowed:true,role:'owner',accountUserId:'workspace-a',userId:'workspace-a'};globalThis.calendarRedis=new Map();globalThis.calendarWorkspaces=new Map([['workspace-a',{leads:[{id:1}],callLogs:[],profile:{},officeItems:[{id:'one',leadId:1,kind:'appointment',title:'Interested callback',dueAt:'2027-02-01T18:00:00Z',status:'open',amount:0,reminderAt:'',reminderState:'off',createdAt:'2027-01-01T18:00:00Z'}]}]]);const cookies=new Map();globalThis.calendarCookies={get:name=>cookies.get(name),set:(name,value,options)=>options?.maxAge===0?cookies.delete(name):cookies.set(name,{value})};globalThis.fetch=async()=>{throw Error('Unexpected external request')}}
const connection=()=>({refreshToken:'private-refresh',calendarId:'managed',connectedBy:'workspace-a',lastSyncAt:'',pending:0,error:'',events:{}});
test('Outlook owner-only connect uses PKCE, encrypted tokens and rejects replay',async()=>{
 setup();globalThis.calendarAccess.role='agent';assert.equal((await POST(request({action:'connect'}))).status,403);globalThis.calendarAccess.role='owner';assert.equal((await POST(request({action:'connect'},'https://evil.test'))).status,403);const {url}=await (await POST(request({action:'connect'}))).json(),q=new URL(url).searchParams;assert.equal(q.get('code_challenge_method'),'S256');let creates=0;
 globalThis.fetch=async(url,options)=>{if(String(url).includes('/token')){assert.ok(options.body.get('code_verifier'));return Response.json({access_token:'access',refresh_token:'private-refresh',scope:'Calendars.ReadWrite'})}assert.equal(url,'https://graph.microsoft.com/v1.0/me/calendars');creates++;return Response.json({id:'managed'})};const req=new Request(`https://crm.test/api/calendar/outlook/callback?code=test&state=${q.get('state')}`);assert.match((await callback(req)).headers.get('location'),/calendar=connected/);assert.match((await callback(req)).headers.get('location'),/calendar=failed/);assert.equal(creates,1);const status=await (await GET()).json();assert.equal(status.showExternal,false);assert.ok(!JSON.stringify(status).includes('private-refresh'));assert.ok(![...globalThis.calendarRedis.values()].join('').includes('private-refresh'));
});
test('Outlook callback rejects changed workspace and missing permission',async()=>{
 setup();let {url}=await (await POST(request({action:'connect'}))).json();globalThis.calendarAccess.accountUserId='other';assert.match((await callback(new Request(`https://crm.test/api/calendar/outlook/callback?code=test&state=${new URL(url).searchParams.get('state')}`))).headers.get('location'),/calendar=failed/);setup();({url}=await (await POST(request({action:'connect'}))).json());globalThis.fetch=async()=>Response.json({access_token:'access',refresh_token:'refresh',scope:'User.Read'});assert.match((await callback(new Request(`https://crm.test/api/calendar/outlook/callback?code=test&state=${new URL(url).searchParams.get('state')}`))).headers.get('location'),/calendar=failed/);assert.equal(await readCalendarSecret('outlook:workspace-a'),null);
});
test('Outlook rotates tokens, creates once, reschedules and deletes only mapped events',async()=>{
 setup();await writeCalendarSecret('outlook:workspace-a',connection());const calls=[];globalThis.fetch=async(url,options)=>{if(String(url).includes('/token'))return Response.json({access_token:'access',refresh_token:'rotated'});calls.push({url,method:options.method,body:options.body&&JSON.parse(options.body)});return options.method==='DELETE'?new Response(null,{status:204}):Response.json({id:'event-one'})};assert.equal((await POST(request({action:'sync'}))).status,200);assert.equal((await readCalendarSecret('outlook:workspace-a')).refreshToken,'rotated');assert.equal(calls[0].body.attendees,undefined);assert.ok(calls[0].body.transactionId);await POST(request({action:'sync'}));assert.equal(calls.length,1);globalThis.calendarWorkspaces.get('workspace-a').officeItems[0].dueAt='2027-02-02T18:00:00Z';await POST(request({action:'sync'}));assert.equal(calls[1].method,'PATCH');assert.equal(calls[1].body.transactionId,undefined);globalThis.calendarWorkspaces.get('workspace-a').officeItems[0].status='done';await POST(request({action:'sync'}));assert.equal(calls[2].method,'DELETE');assert.match(calls[2].url,/managed\/events\/event-one$/);
});
test('imports are opt-in, deduplicate, preserve all-day dates, and never enter workspace data',async()=>{
 setup();const req=new Request('https://crm.test/api/calendar/external?start=2027-02-01&end=2027-03-01');assert.deepEqual((await (await externalGet(req)).json()).events,[]);await writeCalendarSecret('workspace-a',{...connection(),showExternal:true,canReadExternal:true});const before=JSON.stringify([...globalThis.calendarWorkspaces]);const event={id:'outside',summary:'Personal event',start:{date:'2027-02-01'},attendees:[{email:'hidden@test'}]};globalThis.fetch=async url=>String(url).includes('/token')?Response.json({access_token:'access'}):Response.json({items:[event,event,{id:'copy',start:{date:'2027-02-01'},extendedProperties:{private:{pacificaId:'one'}}}]});const data=await (await externalGet(req)).json();assert.equal(data.events.length,1);assert.equal(data.events[0].dueAt,'2027-02-01T12:00:00');assert.equal(data.events[0].reminderState,'off');assert.equal(data.events[0].attendees,undefined);assert.equal(JSON.stringify([...globalThis.calendarWorkspaces]),before);assert.equal(normalizeExternalEvent('outlook',{id:'x',isCancelled:true,start:{dateTime:'2027-02-01T18:00:00'}}),null);assert.equal(normalizeExternalEvent('outlook',{id:'x',start:{dateTime:'2027-02-01T18:00:00'},webLink:'https://evil.test'}).externalUrl,'');assert.equal((await externalGet(new Request('https://crm.test/api/calendar/external?start=2027-01-01&end=2028-01-01'))).status,400);
});
test('private feeds require owner creation, revoke URLs, exclude cold follow-ups and escape ICS',async()=>{
 setup();globalThis.calendarWorkspaces.get('workspace-a').leads.push({id:2,followUp:'2027-02-01T12:00:00Z'});globalThis.calendarAccess.role='agent';assert.equal((await feedPost(request({action:'connect'}))).status,403);globalThis.calendarAccess.role='owner';const {url}=await (await feedPost(request({action:'connect'}))).json();const feed=await feedGet(new Request(url));assert.equal(feed.status,200);const content=await feed.text();assert.equal(content.split('BEGIN:VEVENT').length,2);assert.match(content,/Interested callback/);await feedPost(request({action:'disconnect'}));assert.equal((await feedGet(new Request(url))).status,403);const escaped=calendarFeed([{...globalThis.calendarWorkspaces.get('workspace-a').officeItems[0],title:'Hello\nATTENDEE:evil;value,'+'🛡️'.repeat(40)}],'workspace-a');assert.ok(escaped.includes('Hello\\nATTENDEE:evil\\;value\\,'));for(const line of escaped.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);
});
