import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
class Contents extends EventEmitter{sent=[];url='';send(...args){this.sent.push(args)}setWindowOpenHandler(){}getURL(){return this.url}}
class Window extends EventEmitter{static instances=[];constructor(options){super();this.options=options;this.webContents=new Contents();this.visible=false;this.position=[0,0];this.size=[options.width,options.height];Window.instances.push(this)}loadURL(url){this.webContents.url=url;return Promise.resolve()}loadFile(){this.loads=(this.loads||0)+1;queueMicrotask(()=>this.webContents.emit('did-finish-load'));return Promise.resolve()}getBounds(){return {x:0,y:0,width:1440,height:900}}getSize(){return this.size}getPosition(){return this.position}setPosition(x,y){this.position=[x,y]}setSize(w,h){this.size=[w,h]}setMinimumSize(){}setAlwaysOnTop(){}setVisibleOnAllWorkspaces(){}isDestroyed(){return false}isMinimized(){return false}isVisible(){return this.visible}hide(){this.visible=false}show(){this.visible=true}showInactive(){this.visible=true;this.inactive=true}focus(){this.focused=true}flashFrame(){}setTitleBarOverlay(){}restore(){}setSkipTaskbar(){}}
test('desktop alerts reject untrusted senders, deduplicate messages, open the right thread and keep calls above other windows',async()=>{
 const app=new EventEmitter();app.whenReady=()=>Promise.resolve();app.getPath=()=>'/tmp/pacifica-test-does-not-exist';const ipcMain=new EventEmitter();ipcMain.handle=()=>{};
 globalThis.desktopHarness={app,ipcMain,BrowserWindow:Window};const originalTimeout=globalThis.setTimeout;globalThis.setTimeout=(fn,ms)=>[5000,6000].includes(ms)?0:originalTimeout(fn,ms);
 try{await import('../../desktop/main.mjs');await Promise.resolve();const main=Window.instances[0];const message={id:'m1',leadId:42,name:'Test Person',body:'A'.repeat(500),channel:'sms'};
  ipcMain.emit('pacifica:message-state',{sender:main.webContents,senderFrame:{url:'https://evil.example'}},message);assert.equal(Window.instances.length,1);
  const event={sender:main.webContents,senderFrame:{url:'https://pacificacrm.com/dashboard'}};ipcMain.emit('pacifica:message-state',event,message);await Promise.resolve();const popup=Window.instances[1];assert.equal(popup.options.alwaysOnTop,true);assert.equal(popup.options.webPreferences.sandbox,true);assert.equal(popup.inactive,true);assert.equal(popup.webContents.sent.at(-1)[1].body.length,240);
  ipcMain.emit('pacifica:message-state',event,message);ipcMain.emit('pacifica:message-action',{sender:popup.webContents},'open');assert.equal(popup.visible,false);assert.equal(main.webContents.sent.at(-1)[0],'pacifica:message-open');assert.equal(main.webContents.sent.at(-1)[1].leadId,42);assert.equal(main.focused,true);
  ipcMain.emit('pacifica:call-state',event,{active:false,incoming:{name:'Incoming',number:'8185550100'}});await Promise.resolve();const call=Window.instances[2];assert.equal(call.options.alwaysOnTop,true);assert.equal(call.visible,false);ipcMain.emit('pacifica:overlay-rendered',{sender:call.webContents});assert.equal(call.visible,true);call.emit('ready-to-show');assert.equal(call.visible,true);assert.equal(call.focused,true);call.webContents.emit('unresponsive');assert.equal(call.visible,false);assert.equal(call.loads,2);await Promise.resolve();ipcMain.emit('pacifica:overlay-rendered',{sender:call.webContents});assert.equal(call.visible,true);call.webContents.emit('unresponsive');assert.equal(call.visible,false);assert.equal(call.loads,2);assert.equal(main.webContents.sent.at(-1)[0],'pacifica:overlay-error');assert.match(main.webContents.sent.at(-1)[1],/Keep using the call controls/);
  ipcMain.emit('pacifica:message-state',event,{...message,id:'m2'});assert.equal(popup.visible,true);main.webContents.emit('did-navigate',{},'https://pacificacrm.com/login');assert.equal(popup.visible,false);
 }finally{globalThis.setTimeout=originalTimeout}
});
