'use client';
import {useEffect,useState} from 'react';
import styles from './quote-request.module.css';
type Info={business:string;existingContact:boolean;consentText:string;expiresAt:string};
export default function QuoteRequestForm(){
 const [info,setInfo]=useState<Info|null>(null),[token,setToken]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{const value=window.location.hash.slice(1);let canceled=false;
  fetch('/api/quote-intake',{headers:{Authorization:`Bearer ${value}`},cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);if(!canceled){setToken(value);setInfo(data)}}).catch(()=>{if(!canceled)setError('This quote link is unavailable or expired. Ask your agent for a new link.')});
  return()=>{canceled=true};
 },[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();if(busy)return;setBusy(true);setError('');const form=new FormData(event.currentTarget),body=Object.fromEntries(form.entries());
  try{const response=await fetch('/api/quote-intake',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({...body,contactPermission:form.get('contactPermission')==='on'})});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to submit your request.');setDone(true)}catch(e){setError(e instanceof Error?e.message:'Unable to submit. Please try again.')}finally{setBusy(false)}
 }
 return <main className={styles.page}><div className={styles.card}><span className={styles.brand}>{info?.business||'Insurance quote request'}</span>{done?<section role="status"><h1>Thank you. Your agent has your request.</h1><p>The agency will review your details and contact you about the next step. Coverage has not been bound.</p></section>:<><h1>{info?.existingContact?'Complete your quote details':'Let’s find your next insurance option.'}</h1><p>{info?.existingContact?'Provide your date of birth so your agent can continue preparing your quote.':'Tell us what you need. Your agent will review your request personally.'}</p>{error&&<p role="alert" className={styles.error}>{error}</p>}{!info&&!error&&<p role="status">Opening your secure form…</p>}{info&&<form onSubmit={submit}><fieldset disabled={busy} className={styles.fields}>
 {!info.existingContact&&<><label>Full name<input name="name" autoComplete="name" required maxLength={100}/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required maxLength={30}/></label><label>Email (optional)<input name="email" type="email" autoComplete="email" maxLength={200}/></label><label>Insurance type<select name="product" required defaultValue=""><option value="" disabled>Choose insurance</option>{['Auto','Home','Renters','Life','Commercial','Home & Auto'].map(p=><option key={p}>{p}</option>)}</select></label><label className={styles.wide}>Street address<input name="address" autoComplete="street-address" required maxLength={160}/></label><label>City<input name="city" autoComplete="address-level2" required maxLength={100}/></label><label>State<input name="state" autoComplete="address-level1" placeholder="CA" minLength={2} maxLength={2} required/></label><label>ZIP code<input name="zip" autoComplete="postal-code" inputMode="numeric" required maxLength={10}/></label></>}
 <label>Date of birth<input name="dateOfBirth" type="date" autoComplete="bday" max={new Date().toISOString().slice(0,10)} required/></label>
 <p className={styles.wide}>Your date of birth is used to prepare your insurance quote. This form does not display any information already on your contact record.</p>
 <label>Upcoming renewal date (optional)<input name="renewalDate" type="date" min={new Date().toISOString().slice(0,10)}/></label><label>Current insurance company (optional)<input name="currentCarrier" maxLength={100}/></label><label className={styles.wide}>VIN (optional)<input name="vin" minLength={17} maxLength={17} autoCapitalize="characters" placeholder="17 characters, if available"/></label>
 <label className={styles.trap} aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>
 <label className={`${styles.consent} ${styles.wide}`}><input type="checkbox" name="contactPermission" required/><span>{info.consentText}</span></label><p className={styles.wide}>Do not enter a Social Security number, payment details, or account password. <a href="/privacy" target="_blank" rel="noreferrer">Privacy</a> · <a href="/terms" target="_blank" rel="noreferrer">Terms</a></p>
 <button className={styles.wide} type="submit">{busy?'Submitting…':'Request my quote'}</button></fieldset></form>}</>}</div></main>
}
