import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Pacifica CRM",
  description: "Terms governing access to Pacifica CRM and its calling and messaging services.",
};

export default function TermsPage() {
  return <main className="terms-page"><article>
    <span>PACIFICA CRM</span><h1>Terms of Service</h1><p className="terms-updated">Effective September 1, 2026</p>
    <p>These Terms of Service govern access to and use of Pacifica CRM, including its lead-management, calling, messaging, scheduling, reporting, and related services. By creating an account or using Pacifica CRM, you agree to these Terms and our <Link href="/privacy">Privacy Policy</Link>.</p>
    <h2>1. Eligibility and accounts</h2><p>You must be legally able to enter into a binding agreement and provide accurate account and business information. You are responsible for protecting your credentials and for all activity performed through your account. Notify Pacifica CRM promptly if you believe your account has been accessed without authorization.</p>
    <h2>2. Authorized business use</h2><p>Pacifica CRM is intended for legitimate business communications by authorized users. You are responsible for every campaign, lead source, caller, representation, and transaction conducted through your account, including any professional or industry licensing requirements that apply to your business.</p>
    <h2>3. Calling and messaging consent</h2><p>You may contact a person through Pacifica CRM only when you have a lawful basis and all consent required for that communication. You must maintain reliable consent records, honor applicable federal and state Do Not Call requirements, and immediately honor company-specific do-not-call and text-message opt-out requests. You may not use purchased, scraped, deceptive, or unlawfully obtained contact information.</p>
    <h2>4. Pacifica CRM text-message program</h2><p>When a person directly opts in to receive text messages from Pacifica CRM, messages may include responses to inquiries, account or service updates, appointment scheduling and reminders, requested follow-ups, customer support, and occasional promotional information. Message frequency varies. Message and data rates may apply. Consent to receive promotional text messages is not a condition of purchase. Reply STOP to cancel future text messages or HELP for assistance. Carriers are not liable for delayed or undelivered messages.</p>
    <h2>5. Calling practices</h2><p>You must comply with the Telephone Consumer Protection Act, Telemarketing Sales Rule, applicable state laws, calling-hour restrictions, caller-identification requirements, abandonment limits, and carrier rules. Pacifica CRM may enforce pacing, attempt-frequency, suppression, consent, and account-suspension controls.</p>
    <h2>6. Recording and automated features</h2><p>Before recording, transcribing, monitoring, or analyzing a communication, you must provide all legally required disclosures and obtain all required consent. Pacifica CRM features do not replace your obligation to obtain consent or independently review automated drafts, suggestions, and outputs before using them.</p>
    <h2>7. Customer data and acceptable use</h2><p>You may upload only data you are authorized to possess and process. You may not use Pacifica CRM for fraud, harassment, unlawful discrimination, impersonation, misleading caller identification, prohibited content, or any attempt to bypass compliance or security controls. We may investigate complaints and suspend or terminate activity that creates legal, security, carrier, or platform risk.</p>
    <h2>8. Third-party services</h2><p>Pacifica CRM may interoperate with third-party providers for communications, identity, payments, hosting, and other functions. Your use of those services may also be governed by their terms. We do not control and are not responsible for third-party service availability, carrier filtering, or external platform decisions.</p>
    <h2>9. Fees and subscriptions</h2><p>Paid features are billed according to the plan and pricing presented at checkout. Communication usage, carrier fees, taxes, and optional integrations may be charged separately. Unless otherwise stated at checkout, subscriptions renew automatically until canceled. Cancellation stops future renewal and does not retroactively refund charges already incurred, except where required by law.</p>
    <h2>10. Service availability and disclaimers</h2><p>Pacifica CRM is provided on an “as available” basis. We do not guarantee uninterrupted availability, deliverability, lead conversion, regulatory compliance for your specific use, or any particular business result. Pacifica CRM does not provide legal, insurance, financial, medical, or other professional advice.</p>
    <h2>11. Changes and termination</h2><p>We may update these Terms to reflect service, legal, or operational changes. Material updates will be posted on this page with a revised effective date. You may stop using the service at any time. Provisions that by their nature should survive termination will remain effective.</p>
    <h2>12. Contact</h2><p>Questions about these Terms or the Pacifica CRM messaging program may be sent to <a href="mailto:support@pacificacrm.com">support@pacificacrm.com</a>.</p>
    <div className="legal-links"><Link href="/">← Return to Pacifica</Link><Link href="/privacy">Privacy Policy</Link></div>
  </article></main>;
}
