"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {kindLabel,captureQuestions,type LeadKind} from '../lib/miner-leads';
export default function LeadCapture(){
 const [token,setToken]=useState(''),[info,setInfo]=useState<{name:string;business:string;kind:LeadKind;consentText:string}|null>(null),[error,setError]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController(),value=window.location.hash.slice(1);void fetch('/api/lead-capture',{signal:controller.signal,headers:{Authorization:`Bearer ${value}`}}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);setToken(value);setInfo(data)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort();},[]);
 async function submit(form:HTMLFormElement){setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(form));const response=await fetch('/api/lead-capture',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({...values,permission:values.permission==='on'})});const data=await response.json();if(!response.ok)throw Error(data.error);setSent(true)}catch(e){setError(e instanceof Error?e.message:'Could not submit.')}finally{setBusy(false)}}
 return <main className="lead-capture-page"><Link href="/">Pacifica</Link>{info?<><span className="eyebrow">{info.business}</span><h1>{sent?'Thank you.':info.name}</h1>{sent?<p>Your {kindLabel[info.kind].toLowerCase()} request is with your advisor. They will review it and get in touch.</p>:<><p>Tell us what you need. Your advisor will follow up personally.</p><form onSubmit={e=>{e.preventDefault();void submit(e.currentTarget)}}><label>Name<input name="name" required autoComplete="name" maxLength={140}/></label><div><label>Phone<input name="phone" type="tel" autoComplete="tel"/></label><label>Email<input name="email" type="email" autoComplete="email"/></label></div><label>ZIP code<input name="zip" required inputMode="numeric" pattern="[0-9]{5}" maxLength={5} autoComplete="postal-code"/></label>{captureQuestions(info.kind).map(q=><label key={q.name}>{q.label}{q.type==='select'?<select name={q.name} defaultValue=""><option value="">Choose if known</option>{q.options?.map(value=><option key={value}>{value}</option>)}</select>:<input name={q.name} type={q.type} maxLength={160} {...(q.type==='number'?{min:0,max:1000000,step:'any'}:{})}/>}</label>)}<label>{info.kind==='real-estate'?'Are you buying or selling? Describe the property, area and timing.':info.kind==='auto'?'Vehicle year/make/model or other details (optional)':info.kind==='home'?'Property or coverage details (optional)':'Business name, operations and coverage you want to discuss'}<textarea name="details" rows={5} maxLength={2000}/></label><label className="lead-capture-consent"><input name="permission" type="checkbox" required/>{info.consentText}</label><label hidden>Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button className="primary" disabled={busy}>{busy?'Sending…':'Request a response'}</button><p className="lead-capture-fine">No purchase is required. Do not include Social Security numbers, payment information or passwords. <Link href="/privacy">Privacy</Link></p></form></>}</>:<h1>{error?'Form unavailable':'Loading…'}</h1>}{error&&<p role="alert">{error}</p>}</main>;
}
