import {cookies} from 'next/headers';
import {getPacificaAccess} from '../../../../lib/clerk-access';
import {outlookConfig,outlookTokens,outlookRequest,outlookKey,type OutlookConnection} from '../../../../lib/outlook-calendar';
import {openCalendar,readCalendarSecret,writeCalendarSecret,withCalendarLock} from '../../../../lib/calendar-vault';
export const runtime='nodejs';export const maxDuration=60;
export async function GET(request:Request){
 const c=outlookConfig();if(!c.ready)return Response.json({error:'Outlook Calendar is not configured.'},{status:503});const destination=new URL('/dashboard',c.redirectUri),jar=await cookies();
 try{const a=await getPacificaAccess(),query=new URL(request.url).searchParams,state=openCalendar<{nonce:string;verifier:string;workspaceId:string;userId:string;expires:number}>(query.get('state')||'','outlook-oauth');const nonce=jar.get('pacifica_outlook_oauth')?.value;jar.set('pacifica_outlook_oauth','',{path:'/api/calendar/outlook',maxAge:0});
 if(!a.allowed||a.role!=='owner'||a.accountUserId!==a.userId||state.userId!==a.accountUserId||state.workspaceId!==a.userId||!Number.isFinite(state.expires)||state.expires<Date.now()||!nonce||nonce!==state.nonce||!state.verifier)throw Error('Invalid authorization.');if(query.has('error')||!query.get('code'))throw Error('Authorization canceled.');
 await withCalendarLock(outlookKey(a.userId),async()=>{const t=await outlookTokens({grant_type:'authorization_code',code:query.get('code')!,redirect_uri:c.redirectUri,code_verifier:state.verifier});if(!t.refresh_token||!t.scope?.split(' ').some(scope=>/^(https:\/\/graph.microsoft.com\/)?Calendars.ReadWrite$/i.test(scope)))throw Error('Calendar permission not granted.');const old=await readCalendarSecret<OutlookConnection>(outlookKey(a.userId));let calendarId='';if(old)try{await outlookRequest(t.access_token!,`me/calendars/${encodeURIComponent(old.calendarId)}`);calendarId=old.calendarId}catch(e){if(![403,404,410].includes(Number((e as {status?:number}).status)))throw e}if(!calendarId){const calendar=await outlookRequest(t.access_token!,'me/calendars','POST',{name:'Pacifica CRM'});calendarId=String(calendar.id||'');if(!calendarId)throw Error('No calendar returned.')}await writeCalendarSecret(outlookKey(a.userId),{refreshToken:t.refresh_token,calendarId,connectedBy:a.accountUserId,lastSyncAt:'',error:'',pending:0,showExternal:false,events:old?.calendarId===calendarId?old.events:{}} satisfies OutlookConnection)});destination.searchParams.set('calendar','connected');
 }catch{destination.searchParams.set('calendar','failed')}return Response.redirect(destination,303);
}
