const api=window.pacificaOverlay,$=id=>document.getElementById(id);let state={},draftId='',outcome='',pending=false;
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>api.send(b.dataset.action));$('mute').onclick=()=>api.send('mute');
function choose(value){const interested=["Interested","Appointment set"].includes(value);if(interested&&!["Interested","Appointment set"].includes(outcome))$("followup").value="";$("followup-label").textContent=interested?"Agreed time · adds to calendar":"Next attempt · Contacts only";outcome=value;document.querySelectorAll('#outcomes button').forEach(b=>{const selected=b.textContent===value;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});const closed=['Not interested','Wrong number','Sold / Won'].includes(value);$('stage').value=closed?'Closed':value==='Appointment set'?'Appointment':state.wrapUp?.wasClosed?'Closed':'Follow-up';if(closed||$('stage').value==='Closed')$('followup').value=''}
function submit(kind){if(pending||!state.wrapUp)return;pending=true;['save','again','pause'].forEach(id=>$(id).disabled=true);$('error').hidden=true;api.sendWrapAction({id:state.wrapUp.id,kind,outcome,stage:$('stage').value,appointmentAt:$('followup').value,notes:$('notes').value})}
$('save').onclick=()=>submit('save');$('again').onclick=()=>submit('again');$('pause').onclick=()=>submit('pause');
function renderState(s){state=s;const incoming=!!s.incoming;const vertical=s.layout==='vertical';document.body.dataset.layout=vertical?'vertical':'horizontal';document.querySelectorAll('.layout-toggle').forEach(b=>{const label=vertical?'Switch to horizontal layout':'Switch to vertical layout';b.title=label;b.setAttribute('aria-label',label);b.textContent=vertical?'▤':'▥'});document.body.dataset.theme=s.theme==='dark'?'dark':'light';document.body.classList.toggle('connected',!!s.connected);const wrap=!!s.wrapUp&&!s.active&&!incoming;$('incoming').hidden=!incoming;$('call').hidden=incoming||wrap;$('wrap').hidden=!wrap;
 if(incoming){$('incoming-name').textContent=s.incoming.name||'Unknown caller';$('incoming-number').textContent=s.incoming.number||'';$('incoming-category').textContent=[s.incoming.category,s.incoming.busy?'Answering will end the current call':'Ready to answer'].filter(Boolean).join(' · ');api.ready();return}
 if(wrap){const w=s.wrapUp;if(draftId!==w.id){draftId=w.id;$('wrap-name').textContent=w.name||w.number;$('wrap-category').textContent=(w.category||'Call')+' · Call result';$('outcomes').replaceChildren();w.outcomes.forEach(value=>{const b=document.createElement('button');b.textContent=value;b.onclick=()=>choose(value);$('outcomes').appendChild(b)});choose(w.draft.crmOutcome);$('stage').value=w.draft.crmStage;$('followup').value=w.draft.appointmentAt||'';$('notes').value=w.draft.notes||''}
 pending=!!w.saving;$('save').disabled=pending;$('again').disabled=pending||w.doNotCall;$('pause').disabled=pending||!w.resume;$('save').textContent=w.resume?'Save & call next':'Save result';$('pause').textContent=w.resume?'Pause queue':'Queue paused';$('error').textContent=w.error||'';$('error').hidden=!w.error;api.ready();return}
 draftId='';$('name').textContent=s.name||s.number||'Active call';$('name').title=[s.name,s.number].filter(Boolean).join(' · ');$('category').textContent=[s.category,s.queueRunning?'Auto queue':'Single call'].filter(Boolean).join(' · ');$('status').textContent=s.connected?'Live ·':s.statusText||'Connecting…';$('status').title=s.statusText||'';$('timer').textContent=s.elapsed||'00:00';$('timer').hidden=!s.connected;$('mute').textContent=s.muted?'Unmute':'Mute';$('mute').disabled=!s.connected;$('mute').setAttribute('aria-pressed',String(!!s.muted));$('end').textContent=s.connected?'End call':'Cancel';
 api.ready();
}
api.onState(renderState);
api.getState().then(renderState).catch(()=>{$('status').textContent='Open the CRM to continue';api.ready()});
